import 'package:allahor_name/app/modules/choose_language/views/choose_language_view.dart';
import 'package:allahor_name/app/modules/home/views/home_view.dart';
import 'package:get/get.dart';

class SplashController extends GetxController {
 void navigateAfterSomeTime(){
  Future.delayed(Duration(seconds: 0)).then((value) => Get.to(()=>ChooseLanguageView()));
 }
 @override
  void onInit() {
   navigateAfterSomeTime();
    super.onInit();
  }
}
List<Map<String, dynamic>> ninetyNineNamesOfAllah = [
  {
    "index": 1,
    "name": "Ar-Rahman",
    "meaning": "The All-Compassionate",
    "banglaName": "আর-রহমান",
    "banglaMeaning": "সর্বদয়ালু",
    "arabicName": "ٱلرَّحۡمَـٰنُ",
    "arabicMeaning": "الرحمن",
    "hindiName": "अर-रहमान",
    "hindiMeaning": "सबका दयालु",
    "description": {
      "english": "Allah is the All-Compassionate, the Most Merciful.",
      "bangla": "আল্লাহ সর্বদয়ালু, অত্যন্ত দয়ালু।",
      "arabic": "ٱللَّهُ ٱلرَّحۡمَـٰنُ ٱلرَّحِيمُ",
      "hindi": "अल्लाह सबका दयालु, सर्वश्रेष्ठ दयालु हैं।",
    },
    "quranAyat": {
      "english": "The Most Merciful. Taught the Quran, Created man, [And] taught him eloquence. (Surah Ar-Rahman 55:1-4)",
      "bangla": "সর্বদয়ালু। কুরআন শেখালেন। মানুষ সৃষ্টি করেন। [আর] তাকে সংবাদে মাহি দিয়েছেন। (সূরা আর-রহমান ৫৫:১-৪)",
      "arabic": "ٱلرَّحۡمَـٰنُ (١) عَلَّمَ ٱلۡقُرۡءَانَ (٢) خَلَقَ ٱلۡإِنسَـٰنَ (٣) عَلَّمَهُ ٱلۡبَيَانَ (٤) (سورة الرحمن 55:1-4)",
      "hindi": "सर्वदयालु। कुरान की शिक्षा दी, आदमी को बनाया, [और] उसे बयान सिखाया। (सूरह अर-रहमान 55:1-4)",
    },
  },
  {
    "index": 2,
    "name": "Ar-Rahim",
    "meaning": "The Most Merciful",
    "banglaName": "আর-রহিম",
    "banglaMeaning": "অত্যন্ত দয়ালু",
    "arabicName": "ٱلرَّحِيمُ",
    "arabicMeaning": "الرحيم",
    "hindiName": "अर-रहीम",
    "hindiMeaning": "सर्वश्रेष्ठ दयालु",
    "description": {
      "english": "Allah is the Most Merciful, the Compassionate.",
      "bangla": "আল্লাহ সর্বদয়ালু, অত্যন্ত দয়ালু।",
      "arabic": "ٱللَّهُ ٱلرَّحۡمَـٰنُ ٱلرَّحِيمُ",
      "hindi": "अल्लाह सबका दयालु, सर्वश्रेष्ठ दयालु हैं।",
    },
    "quranAyat": {
      "english": "The Most Merciful, Taught the Quran, Created man, [And] taught him eloquence. (Surah Ar-Rahman 55:1-4)",
      "bangla": "সর্বদয়ালু। কুরআন শেখালেন। মানুষ সৃষ্টি করেন। [আর] তাকে সংবাদে মাহি দিয়েছেন। (সূরা আর-রহমান ৫৫:১-৪)",
      "arabic": "ٱلرَّحۡمَـٰنُ (١) عَلَّمَ ٱلۡقُرۡءَانَ (٢) خَلَقَ ٱلۡإِنسَـٰنَ (٣) عَلَّمَهُ ٱلۡبَيَانَ (٤) (سورة الرحمن 55:1-4)",
      "hindi": "सर्वदयालु। कुरान की शिक्षा दी, आदमी को बनाया, [और] उसे बयान सिखाया। (सूरह अर-रहमान 55:1-4)",
    },
  },
  {
    "index": 3,
    "name": "Al-Malik",
    "meaning": "The Absolute Ruler",
    "banglaName": "আল-মালিক",
    "banglaMeaning": "পরম প্রভু",
    "arabicName": "ٱلۡمَلِكُ",
    "arabicMeaning": "الملك",
    "hindiName": "अल-मालिक",
    "hindiMeaning": "परम प्रभु",
    "description": {
      "english": "Allah is the King, the Sovereign.",
      "bangla": "আল্লাহ রাজা, মহারাজা।",
      "arabic": "ٱللَّهُ ٱلۡمَلِكُ ٱلۡمُقۡتَدِرُ",
      "hindi": "अल्लाह राजा, अधिपति हैं।",
    },
    "quranAyat": {
      "english": "Allah - there is no deity except Him, the Ever-Living, the Sustainer of [all] existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is [presently] before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great. (Surah Al-Baqarah 2:255)",
      "bangla": "আল্লাহ - তার বাইরে কোন প্রতিমা নেই, চিরস্থায়ী, সমস্ত অস্তিত্বের ধারক। যে কোনও অলসতা তাকে লাগে না এবং নিদ্রা আসে না। আকাশে যা কিছু আছে এবং পৃথিবীতে যা কিছু আছে তা তার জন্য। তার অনুমতি ছাড়া কে তার সাথে বিচার করতে পারে? তিনি তাদের আগে কি আছে এবং তারা পরে কি হবে তা জানেন এবং তারা তার জ্ঞানের কোনও ব্যক্তির চেয়ে বেশী জিজ্ঞাসা করেন না, ব্যর্থ এমন কোনও কিছু ছাড়া। তার কুরসি আকাশ ও পৃথিবীর উপর প্রসারিত আছে, এবং তার রক্ষণাবেক্ষণ তাকে ক্লান্ত করে না। এবং তিনি সর্বোচ্চ, সর্বমহান। (সূরা আল-বাকারা ২:২৫৫)",
      "arabic": "ٱللَّهُ لَآ إِلَـٰهَ إِلَّا هُوَ ٱلۡحَىُّ ٱلۡقَيُّومُ‌ۚ لَا تَأۡخُذُهُ ۥ سِنَةٌ۬ وَلَا نَوۡمٌ۬‌ۚ لَّهُ ۥ مَا فِى ٱلسَّمَـٰوَٲتِ وَمَا فِى ٱلۡأَرۡضِ‌ۗ مَن ذَا ٱلَّذِى يَشۡفَعُ عِندَهُ ۥۤ إِلَّا بِإِذۡنِهِۦ‌ۚ يَعۡلَمُ مَا بَيۡنَ أَيۡدِيهِمۡ وَمَا خَلۡفَهُمۡ‌ۖ وَلَا يُحِيطُونَ بِشَىۡءٍ۬ مِّنۡ عِلۡمِهِۦۤ إِلَّا بِمَا شَآءَ‌ۚ وَسِعَ كُرۡسِيُّهُ ٱلسَّمَـٰوَٲتِ وَٱلۡأَرۡضَ‌ۖ وَلَا يَـُٔودُهُ ۥ حِفۡظُهُمَا‌ۚ وَهُوَ ٱلۡعَلِىُّ ٱلۡعَظِيمُ (سورة البقرة 2:255)",
      "hindi": "अल्लाह - उसके सिवा कोई प्रभु नहीं, जो सदा जीवित है, समस्त अस्तित्व का पोषण करने वाला। न उसे झपकी लगती है न नींद। उसके पास जो कुछ आसमानों में है और जो कुछ पृथ्वी पर है, वह सब उसके लिए है। कौन है जो उसके अनुमति के बिना उसके पास बिचार कर सकता है? वह जानता है उनके सामने क्या है और उनके पीछे क्या होगा, और वे उसके ज्ञान की कोई चीज़ के बारे में जिसका वह नहीं चाहता, समझते नहीं हैं। उसकी कुर्सी आसमानों और पृथ्वी के ऊपर फैली हुई है, और उनकी संरक्षा उन्हें थका नहीं देती। और वह सर्वोच्च, सर्वमहान है। (सूरह अल-बकाराह 2:255)",
    },
  },
  {
    "index": 4,
    "name": "Al-Quddus",
    "meaning": "The Pure One",
    "banglaName": "আল-কুদ্দুস",
    "banglaMeaning": "নিষ্পাপ",
    "arabicName": "ٱلۡقُدُّوسُ",
    "arabicMeaning": "القدوس",
    "hindiName": "अल-क़ुद्दूस",
    "hindiMeaning": "शुद्ध",
    "description": {
      "english": "Allah is the Pure One, the Holy.",
      "bangla": "আল্লাহ নিষ্পাপ, পবিত্র।",
      "arabic": "ٱللَّهُ ٱلۡقُدُّوسُ",
      "hindi": "अल्लाह पवित्र, पवित्र हैं।",
    },
    "quranAyat": {
      "english": "Allah is the Pure. (Surah Al-Hashr 59:23)",
      "bangla": "আল্লাহ শুধু পবিত্র। (সূরা আল-হাশর ৫৯:২৩)",
      "arabic": "ٱللَّهُ ٱلۡقُدُّوسُ (سورة الحشر 59:23)",
      "hindi": "अल्लाह पवित्र हैं। (सूरह अल-हाशर 59:23)",
    },
  },
  {
    "index": 5,
    "name": "As-Salam",
    "meaning": "The Source of Peace",
    "banglaName": "আস-সালাম",
    "banglaMeaning": "শান্তির উৎস",
    "arabicName": "ٱلسَّلَـٰمُ",
    "arabicMeaning": "السلام",
    "hindiName": "अस-सलाम",
    "hindiMeaning": "शांति का स्रोत",
    "description": {
      "english": "Allah is the Source of Peace, the Bestower of Security.",
      "bangla": "আল্লাহ শান্তির উৎস, সুরক্ষার দাতা।",
      "arabic": "ٱللَّهُ ٱلسَّلَـٰمُ",
      "hindi": "अल्लाह शांति का स्रोत, सुरक्षा देने वाला हैं।",
    },
    "quranAyat": {
      "english": "Allah - there is no deity except Him, the Ever-Living, the Sustainer of [all] existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is [presently] before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great. (Surah Al-Baqarah 2:255)",
      "bangla": "আল্লাহ - তার বাইরে কোন প্রতিমা নেই, চিরস্থায়ী, সমস্ত অস্তিত্বের ধারক। যে কোনও অলসতা তাকে লাগে না এবং নিদ্রা আসে না। আকাশে যা কিছু আছে এবং পৃথিবীতে যা কিছু আছে তা তার জন্য। তার অনুমতি ছাড়া কে তার সাথে বিচার করতে পারে? তিনি তাদের আগে কি আছে এবং তারা পরে কি হবে তা জানেন এবং তারা তার জ্ঞানের কোনও ব্যক্তির চেয়ে বেশী জিজ্ঞাসা করেন না, ব্যর্থ এমন কোনও কিছু ছাড়া। তার কুর্সী আকাশ ও পৃথিবীর উপর প্রসারিত আছে, এবং তার রক্ষণাবেক্ষণ তাকে ক্লান্ত করে না। এবং তিনি সর্বোচ্চ, সর্বমহান। (সূরা আল-বাকারা ২:২৫৫)",
      "arabic": "ٱللَّهُ لَآ إِلَـٰهَ إِلَّا هُوَ ٱلۡحَىُّ ٱلۡقَيُّومُ‌ۚ لَا تَأۡخُذُهُ ۥ سِنَةٌ۬ وَلَا نَوۡمٌ۬‌ۚ لَّهُ ۥ مَا فِى ٱلسَّمَـٰوَٲتِ وَمَا فِى ٱلۡأَرۡضِ‌ۗ مَن ذَا ٱلَّذِى يَشۡفَعُ عِندَهُ ۥۤ إِلَّا بِإِذۡنِهِۦ‌ۚ يَعۡلَمُ مَا بَيۡنَ أَيۡدِيهِمۡ وَمَا خَلۡفَهُمۡ‌ۖ وَلَا يُحِيطُونَ بِشَىۡءٍ۬ مِّنۡ عِلۡمِهِۦۤ إِلَّا بِمَا شَآءَ‌ۚ وَسِعَ كُرۡسِيُّهُ ٱلسَّمَـٰوَٲتِ وَٱلۡأَرۡضَ‌ۖ وَلَا يَـُٔودُهُ ۥ حِفۡظُهُمَا‌ۚ وَهُوَ ٱلۡعَلِىُّ ٱلۡعَظِيمُ (سورة البقرة 2:255)",
      "hindi": "अल्लाह - उसके सिवा कोई प्रभु नहीं, जो सदा जीवित है, समस्त अस्तित्व का पोषण करने वाला। न उसे झपकी लगती है न नींद। उसके पास जो कुछ आसमानों में है और जो कुछ पृथ्वी पर है, वह सब उसके लिए है। कौन है जो उसके अनुमति के बिना उसके पास बिचार कर सकता है? वह जानता है उनके सामने क्या है और उनके पीछे क्या होगा, और वे उसके ज्ञान की कोई चीज़ के बारे में जिसका वह नहीं चाहता, समझते नहीं हैं। उसकी कुर्सी आसमानों और पृथ्वी के ऊपर फैली हुई है, और उनकी संरक्षा उन्हें थका नहीं देती। और वह सर्वोच्च, सर्वमहान है। (सूरह अल-बकाराह 2:255)",
    },
  },
  {
    "index": 6,
    "name": "Al-Mu'min",
    "meaning": "The Bestower of Faith",
    "banglaName": "আল-মুমিন",
    "banglaMeaning": "বিশ্বাস দাতা",
    "arabicName": "ٱلۡمُؤۡمِنُ",
    "arabicMeaning": "المؤمن",
    "hindiName": "अल-मुमीन",
    "hindiMeaning": "विश्वास दाता",
    "description": {
      "english": "Allah is the Granter of Security, the Faithful.",
      "bangla": "আল্লাহ নিরাপদতা দাতা, বিশ্বাসযোগ্য।",
      "arabic": "ٱللَّهُ ٱلۡمُؤۡمِنُ",
      "hindi": "अल्लाह आत्मविश्वास दाता, विश्वसनीय हैं।",
    },
    "quranAyat": {
      "english": "Allah is the Granter of Security. (Surah Al-Hashr 59:23)",
      "bangla": "আল্লাহ নিরাপদতা দাতা। (সূরা আল-হাশর ৫৯:২৩)",
      "arabic": "ٱللَّهُ ٱلۡمُؤۡمِنُ (سورة الحشر 59:23)",
      "hindi": "अल्लाह आत्मविश्वास दाता। (सूरह अल-हाशर 59:23)",
    },
  },
  {
    "index": 7,
    "name": "Al-Muhaymin",
    "meaning": "The Guardian",
    "banglaName": "আল-মুহায়মিন",
    "banglaMeaning": "রক্ষক",
    "arabicName": "ٱلۡمُۥۤہَيۡمِنُ",
    "arabicMeaning": "المهيمن",
    "hindiName": "अल-मुहय्मिन",
    "hindiMeaning": "संरक्षक",
    "description": {
      "english": "Allah is the Guardian, the Preserver of Safety.",
      "bangla": "আল্লাহ রক্ষক, নিরাপত্তার রক্ষক।",
      "arabic": "ٱللَّهُ ٱلۡمُۥۤہَيۡمِنُ",
      "hindi": "अल्लाह संरक्षक, सुरक्षा की हिफाजত करने वाले हैं।",
    },
    "quranAyat": {
      "english": "Allah is the Guardian. (Surah Al-Hashr 59:23)",
      "bangla": "আল্লাহ রক্ষক। (সূরা আল-হাশর ৫৯:২৩)",
      "arabic": "ٱللَّهُ ٱلۡمُۥۤہَيۡمِنُ (سورة الحشر 59:23)",
      "hindi": "अल्लाह संरक्षक। (सूरह अल-हाशर 59:23)",
    },
  },
  {
    "index": 8,
    "name": "Al-Aziz",
    "meaning": "The Almighty",
    "banglaName": "আল-আজিজ",
    "banglaMeaning": "সর্বশক্তিমান",
    "arabicName": "ٱلۡعَزِيزُ",
    "arabicMeaning": "العزيز",
    "hindiName": "अल-आजिज़",
    "hindiMeaning": "सर्वशक्तिमान",
    "description": {
      "english": "Allah is the Almighty, the Self-Sufficient.",
      "bangla": "আল্লাহ সর্বশক্তিমান, স্বতন্ত্র।",
      "arabic": "ٱللَّهُ ٱلۡعَزِيزُ ٱلۡجَبَّارُ",
      "hindi": "अल्लाह सर्वशक्तिमान, स्वतंत्र हैं।",
    },
    "quranAyat": {
      "english": "Allah is the Almighty, the Self-Sufficient. (Surah Al-Hashr 59:23)",
      "bangla": "আল্লাহ সর্বশক্তিমান, স্বতন্ত্র। (সূরা আল-হাশর ৫৯:২৩)",
      "arabic": "ٱللَّهُ ٱلۡعَزِيزُ ٱلۡجَبَّارُ (سورة الحشر 59:23)",
      "hindi": "अल्लाह सर्वशक्तिमान, स्वतंत्र हैं। (सूरह अल-हाशर 59:23)",
    },
  },
  {
    "index": 9,
    "name": "Al-Jabbar",
    "meaning": "The Compeller",
    "banglaName": "আল-জব্বার",
    "banglaMeaning": "মাঝারি",
    "arabicName": "ٱلۡجَبَّارُ",
    "arabicMeaning": "الجبار",
    "hindiName": "अल-जब्बार",
    "hindiMeaning": "मजबूर करने वाला",
    "description": {
      "english": "Allah is the Compeller, the Restorer of Order.",
      "bangla": "আল্লাহ মাঝারি, বিনিয়োগের পুনর্স্থাপক।",
      "arabic": "ٱللَّهُ ٱلۡعَزِيزُ ٱلۡجَبَّارُ",
      "hindi": "अल्लाह मजबूर करने वाला, व्यवस्था का पुनर्स्थापक हैं।",
    },
    "quranAyat": {
      "english": "Allah is the Compeller. (Surah Al-Hashr 59:23)",
      "bangla": "আল্লাহ মাঝারি। (সূরা আল-হাশর ৫৯:২৩)",
      "arabic": "ٱللَّهُ ٱلۡجَبَّارُ (سورة الحشر 59:23)",
      "hindi": "अल्लाह मजबूर करने वाला हैं। (सूरह अल-हाशर 59:23)",
    },
  },
  {
    "index": 10,
    "name": "Al-Mutakabbir",
    "meaning": "The Majestic",
    "banglaName": "আল-মুতক্ব্বির",
    "banglaMeaning": "অহংকারী",
    "arabicName": "ٱلۡمُتَكَبِّرُ",
    "arabicMeaning": "المتكبر",
    "hindiName": "अल-मुतकब्बिर",
    "hindiMeaning": "घमণ্ডी",
    "description": {
      "english": "Allah is the Majestic, the Supreme.",
      "bangla": "আল্লাহ অহংকারী, সর্বোচ্চ।",
      "arabic": "ٱللَّهُ ٱلۡمُتَكَبِّرُ",
      "hindi": "अल्लाह घमণ্ডी, सर्वोच्च हैं।",
    },
    "quranAyat": {
      "english": "Allah is the Majestic. (Surah Al-Hashr 59:23)",
      "bangla": "আল্লাহ অহংকারী। (সূরা আল-হাশর ৫৯:২৩)",
      "arabic": "ٱللَّهُ ٱلۡمُتَكَبِّرُ (سورة الحشر 59:23)",
      "hindi": "अल्लाह घमণ্ডी हैं। (सूरह अल-हाशर 59:23)",
    },
  },
  {
    "index": 11,
    "name": "Al-Khaliq",
    "meaning": "The Creator",
    "banglaName": "আল-খালিক",
    "banglaMeaning": "সৃষ্টিকর্তা",
    "arabicName": "ٱلۡخَـٰلِقُ",
    "arabicMeaning": "الخالق",
    "hindiName": "अल-खालिक़",
    "hindiMeaning": "निर्माता",
    "description": {
      "english": "Allah is the Creator, the Maker.",
      "bangla": "আল্লাহ সৃষ্টিকর্তা, নির্মাতা।",
      "arabic": "ٱللَّهُ ٱلۡخَـٰلِقُ",
      "hindi": "अल्लाह निर्माता, निर्माता हैं।",
    },
    "quranAyat": {
      "english": "He is Allah, the Creator, the Inventor, the Fashioner; to Him belong the best names. Whatever is in the heavens and earth is exalting Him. And He is the Exalted in Might, the Wise. (Surah Al-Hashr 59:24)",
      "bangla": "তিনি আল্লাহ, সৃষ্টিকর্তা, আবিষ্কারক, বস্ত্রনেও; তার কাছে সবচেয়ে সুন্দর নামগুলি অধিক। আকাশ এবং পৃথিবীতে যা কিছু আছে তা তার প্রশংসা করছে। এবং তিনি শক্তিশালী, বুদ্ধিমান। (সূরা আল-হাশর ৫৯:২৪)",
      "arabic": "هُوَ ٱللَّهُ ٱلۡخَـٰلِقُ ٱلۡبَارِئُ ٱلۡمُصَوِّرُ‌ۖ لَهُ ٱلۡأَسۡمَآءُ ٱلۡحُسۡنَىٰ‌ۚ يُسَبِّحُ لَهُ ۥ مَا فِى ٱلسَّمَـٰوَٲتِ وَٱلۡأَرۡضِ‌ۖ وَهُوَ ٱلۡعَزِيزُ ٱلۡحَكِيمُ (سورة الحشر 59:24)",
      "hindi": "वह अल्लाह है, सृष्टिकर्ता, उत्पन्नकर्ता, रूपांतरक; उसी के पास सबसे अच्छे नाम हैं। जो कुछ आसमान और पृथ्वी में है, वह उसकी प्रशंसा कर रहा है। और वह शक्तिशाली, बुद्धिमान हैं। (सूरह अल-हाशर 59:24)",
    },
  },
  {
    "index": 12,
    "name": "Al-Bari",
    "meaning": "The Evolver",
    "banglaName": "আল-বারি",
    "banglaMeaning": "বর্ধক",
    "arabicName": "ٱلۡبَارِئُ",
    "arabicMeaning": "البارئ",
    "hindiName": "अल-बारी",
    "hindiMeaning": "वृद्धि करने वाला",
    "description": {
      "english": "Allah is the Evolver, the Maker.",
      "bangla": "আল্লাহ বর্ধক, নির্মাতা।",
      "arabic": "ٱللَّهُ ٱلۡبَارِئُ",
      "hindi": "अल्लाह वृद्धि करने वाला, निर्माता हैं।",
    },
    "quranAyat": {
      "english": "He is Allah, the Creator, the Inventor, the Fashioner; to Him belong the best names. Whatever is in the heavens and earth is exalting Him. And He is the Exalted in Might, the Wise. (Surah Al-Hashr 59:24)",
      "bangla": "তিনি আল্লাহ, সৃষ্টিকর্তা, আবিষ্কারক, বস্ত্রনেও; তার কাছে সবচেয়ে সুন্দর নামগুলি অধিক। আকাশ এবং পৃথিবীতে যা কিছু আছে তা তার প্রশংসা করছে। এবং তিনি শক্তিশালী, বুদ্ধিমান। (সূরা আল-হাশর ৫৯:২৪)",
      "arabic": "هُوَ ٱللَّهُ ٱلۡخَـٰلِقُ ٱلۡبَارِئُ ٱلۡمُصَوِّرُ‌ۖ لَهُ ٱلۡأَسۡمَآءُ ٱلۡحُسۡنَىٰ‌ۚ يُسَبِّحُ لَهُ ۥ مَا فِى ٱلسَّمَـٰوَٲتِ وَٱلۡأَرۡضِ‌ۖ وَهُوَ ٱلۡعَزِيزُ ٱلۡحَكِيمُ (سورة الحشر 59:24)",
      "hindi": "वह अल्लाह है, सृष्टिकर्ता, उत्पन्नकर्ता, रूपांतरक; उसी के पास सबसे अच्छे नाम हैं। जो कुछ आसमान और पृथ्वी में है, वह उसकी प्रशंसा कर रहा है। और वह शक्तिशाली, बुद्धिमान हैं। (सूरह अल-हाशर 59:24)",
    },
  },
  {
    "index": 13,
    "name": "Al-Musawwir",
    "meaning": "The Fashioner",
    "banglaName": "আল-মুসাওয়ির",
    "banglaMeaning": "আকারদাতা",
    "arabicName": "ٱلۡمُصَوِّرُ",
    "arabicMeaning": "المصور",
    "hindiName": "अल-मुसव्विर",
    "hindiMeaning": "आकार देने वाला",
    "description": {
      "english": "Allah is the Fashioner, the Bestower of Forms.",
      "bangla": "আল্লাহ আকারদাতা, আকৃতি দাতা।",
      "arabic": "ٱللَّهُ ٱلۡخَـٰلِقُ ٱلۡبَارِئُ ٱلۡمُصَوِّرُ",
      "hindi": "अल्लाह आकार देने वाला, आकृति दाता हैं।",
    },
    "quranAyat": {
      "english": "He is Allah, the Creator, the Inventor, the Fashioner; to Him belong the best names. Whatever is in the heavens and earth is exalting Him. And He is the Exalted in Might, the Wise. (Surah Al-Hashr 59:24)",
      "bangla": "তিনি আল্লাহ, সৃষ্টিকর্তা, আবিষ্কারক, বস্ত্রনেও; তার কাছে সবচেয়ে সুন্দর নামগুলি অধিক। আকাশ এবং পৃথিবীতে যা কিছু আছে তা তার প্রশংসা করছে। এবং তিনি শক্তিশালী, বুদ্ধিমান। (সূরা আল-হাশর ৫৯:২৪)",
      "arabic": "هُوَ ٱللَّهُ ٱلۡخَـٰلِقُ ٱلۡبَارِئُ ٱلۡمُصَوِّرُ‌ۖ لَهُ ٱلۡأَسۡمَآءُ ٱلۡحُسۡنَىٰ‌ۚ يُسَبِّحُ لَهُ ۥ مَا فِى ٱلسَّمَـٰوَٲتِ وَٱلۡأَرۡضِ‌ۖ وَهُوَ ٱلۡعَزِيزُ ٱلۡحَكِيمُ (سورة الحشر 59:24)",
      "hindi": "वह अल्लाह है, सृष्टिकर्ता, उत्पन्नकर्ता, रूपांतरक; उसी के पास सबसे अच्छे नाम हैं। जो कुछ आसमान और पृथ्वी में है, वह उसकी प्रशंसा कर रहा है। और वह शक्तिशाली, बुद्धिमान हैं। (सूरह अल-हाशर 59:24)",
    },
  },
  {
    "index": 14,
    "name": "Al-Ghaffar",
    "meaning": "The Forgiver",
    "banglaName": "আল-গফফার",
    "banglaMeaning": "ক্ষমাশীল",
    "arabicName": "ٱلۡغَفَّارُ",
    "arabicMeaning": "الغفار",
    "hindiName": "अल-गफ्फार",
    "hindiMeaning": "क्षमाशील",
    "description": {
      "english": "Allah is the Forgiver, the Pardoner.",
      "bangla": "আল্লাহ ক্ষমাশীল, ক্ষমা করার।",
      "arabic": "ٱللَّهُ ٱلۡغَفَّارُ",
      "hindi": "अल्लाह क्षमाशील, क्षमा करने वाला हैं।",
    },
    "quranAyat": {
      "english": "Surely Allah is Forgiving, Merciful. (Surah Al-Baqarah 2:173)",
      "bangla": "আল্লাহ নিশ্চয়ই ক্ষমাশীল, দয়ালু। (সূরা আল-বাকারা ২:১৭৩)",
      "arabic": "إِنَّ ٱللَّهَ غَفُورٌ۬ رَّحِيمٌ۬ (سورة البقرة 2:173)",
      "hindi": "बेशक अल्लाह बख्शनेवाला, दयालु हैं। (सूरह अल-बकाराह 2:173)",
    },
  },
  {
    "index": 15,
    "name": "Al-Qahhar",
    "meaning": "The Subduer",
    "banglaName": "আল-কাহ্হার",
    "banglaMeaning": "বিজয়ী",
    "arabicName": "ٱلۡقَهَّارُ",
    "arabicMeaning": "القهار",
    "hindiName": "अल-कह्हार",
    "hindiMeaning": "विजयक",
    "description": {
      "english": "Allah is the Subduer, the Dominant.",
      "bangla": "আল্লাহ বিজয়ী, প্রভাবশালী।",
      "arabic": "ٱللَّهُ ٱلۡقَهَّارُ",
      "hindi": "अल्लाह विजयक, प्रभावशाली हैं।",
    },
    "quranAyat": {
      "english": "Surely your Lord is Allah, Who created the heavens and the earth in six periods of time, and He is firm in power; but there is no God but He; the Knower of the unseen and the seen; He is the Beneficent, the Merciful. (Surah Al-A'raf 7:54)",
      "bangla": "নিশ্চয়ই আপনার প্রভু আল্লাহ, যিনি আকাশ এবং পৃথিবীকে ছয় দিনে সৃষ্টি করেছেন এবং তিনি ক্ষমতায় স্থির; কিন্তু তারা ছাড়া আর কোন ঈশ্বর নেই; অদৃশ্য এবং দৃশ্য জানার; তিনি দয়ালু, দয়ালু। (সূরা আল-আ'রাফ ৭:৫৪)",
      "arabic": "إِنَّ رَبَّكُمُ ٱللَّهُ ٱلَّذِى خَلَقَ ٱلسَّمَـٰوَٲتِ وَٱلۡأَرۡضَ فِى سِتَّةِ أَيَّامٍ۬ ثُمَّ ٱسۡتَوَىٰ عَلَى ٱلۡعَرۡشِ‌ۖ يُدَبِّرُ ٱلۡأَمۡرَ‌ۖ مَا مِن شَفِيعٍ إِلَّا مِنۢ بَعۡدِ إِذۡنِهِۦ‌ۚ ذَٲلِكُمُ ٱللَّهُ رَبُّكُمۡ فَٱعۡبُدُوهُ‌ۚ أَفَلَا تَذَكَّرُونَ (سورة الأعراف 7:54)",
      "hindi": "निश्चय ही आपका प्रभु अल्लाह है, जिन्होंने छह दिनों में आसमान और पृथ्वी को पैदा किया, और वे शक्तिशाली हैं; लेकिन उसके सिवा कोई भगवान नहीं है; अदृश्य और दृश्य जाननेवाला; वह दयालु, दयालु हैं। (सूरह अल-आराफ 7:54)",
    },
  },
  {
    "index": 16,
    "name": "Al-Wahhab",
    "meaning": "The Bestower",
    "banglaName": "আল-ওয়াহ্হাব",
    "banglaMeaning": "দাতা",
    "arabicName": "ٱلۡوَهَّابُ",
    "arabicMeaning": "الوهاب",
    "hindiName": "अल-वह्हाब",
    "hindiMeaning": "दाता",
    "description": {
      "english": "Allah is the Bestower, the Giver of Gifts.",
      "bangla": "আল্লাহ দাতা, উপহার দাতা।",
      "arabic": "ٱللَّهُ ٱلۡوَهَّابُ",
      "hindi": "अल्लाह दाता, उपहार दाता हैं।",
    },
    "quranAyat": {
      "english": "Whatever Allah grants to people of mercy - none can withhold it; and whatever He withholds - none can release it thereafter. And He is the Exalted in Might, the Wise. (Surah Fatir 35:2)",
      "bangla": "যে দিয়ে আল্লাহ মানুষের উপর দয়া করেন, তাকে কেউ রোকতে পারে না; এবং যে কিছু তিনি রোকেন, পরবর্তীতে কেউ তা মুক্ত করতে পারে না। এবং তিনি শক্তিশালী, বুদ্ধিমান। (সূরা ফাতির ৩৫:২)",
      "arabic": "مَّا يَفۡتَحِ ٱللَّهُ لِلنَّاسِ مِن رَّحۡمَةٍ۬ فَلَا مُمۡسِكَ لَهَا‌ۖ وَمَا يُمۡسِكۡ فَلَا مُرۡسِلَ لَهُ ۥ مِنۢ بَعۡدِهِۦ‌ۚ وَهُوَ ٱلۡعَزِيزُ ٱلۡحَكِيمُ (سورة فاطر 35:2)",
      "hindi": "जो कुछ अल्लाह मानवता को दया करता है, उसे कोई नहीं रोक सकता; और जो कुछ वह रोकता है, उसको बाद में कोई नहीं छुड़ा सकता। और वह शक्तिशाली, बुद्धिमान हैं। (सूरह फातिर 35:2)",
    },
  },
  {
    "index": 17,
    "name": "Ar-Razzaq",
    "meaning": "The Provider",
    "banglaName": "আর-রজ্জাক",
    "banglaMeaning": "প্রদাতা",
    "arabicName": "ٱلۡرَّزَّاقُ",
    "arabicMeaning": "الرزاق",
    "hindiName": "अर-रज़्ज़ाक",
    "hindiMeaning": "प्रदानकर्ता",
    "description": {
      "english": "Allah is the Provider, the Sustainer.",
      "bangla": "আল্লাহ প্রদাতা, প্রতিপালক।",
      "arabic": "ٱللَّهُ ٱلۡرَّزَّاقُ",
      "hindi": "अल्लाह प्रदानकर्ता, पालनहार हैं।",
    },
    "quranAyat": {
      "english": "And no creature is there on earth but that upon Allah is its provision, and He knows its place of dwelling and place of storage. All is in a clear register. (Surah Hud 11:6)",
      "bangla": "এবং পৃথিবীতে কোন জীবিত জীব নেই যেহেতু আল্লাহর প্রদান করা, এবং তিনি জানেন তার আবাসের এবং সংরক্ষণের স্থান। সব একটি স্পষ্ট নিবন্ধনে আছে। (সূরা হুদ ১১:৬)",
      "arabic": "وَمَا مِن دَآبَّةٍۢ فِى ٱلۡأَرۡضِ إِلَّا عَلَى ٱللَّهِ رِزۡقُهَا وَيَعۡلَمُ مُسۡتَقَرَّهَا وَمُسۡتَوۡدَعَهَا‌ۚ كُلٌّ۬ فِى ڪِتَـٰبٍ۬ مُّبِينٍ۬ (سورة هود 11:6)",
      "hindi": "और जमीन पर कोई जीवन्त प्राणी नहीं है जिसका रिज़्क अल्लाह पर है, और उसे जगह की जानकारी है जहां उसका आवास है और कहां उसका भंडारण है। सब कुछ एक स्पष्ट रेजिस्टर में है। (सूरह हूद 11:6)",
    },
  },
  {
    "index": 18,
    "name": "Al-Fattah",
    "meaning": "The Opener",
    "banglaName": "আল-ফাত্তাহ্‌",
    "banglaMeaning": "খোলার",
    "arabicName": "ٱلۡفَتَّاحُ",
    "arabicMeaning": "الفتاح",
    "hindiName": "अल-फ़त्ताह",
    "hindiMeaning": "खोलनेवाला",
    "description": {
      "english": "Allah is the Opener, the Judge.",
      "bangla": "আল্লাহ খোলার, বিচারক।",
      "arabic": "ٱللَّهُ ٱلۡفَتَّاحُ",
      "hindi": "अल्लाह खोलनेवाला, न्यायाधीश हैं।",
    },
    "quranAyat": {
      "english": "And know that Allah knows what is within yourselves, so beware of Him. And know that Allah is Forgiving and Forbearing. (Surah Al-Baqarah 2:235)",
      "bangla": "আর জান, আল্লাহ আপনাদের মধ্যে যা আছে তার জ্ঞান রাখেন, তাই তাকে সাবধান রাখুন। আর জান, আল্লাহ ছিলেন ক্ষমাশীল এবং ধৈর্যশীল। (সূরা আল-বাকারা ২:২৩৫)",
      "arabic": "وَأَعۡلَمُوٓاْ أَنَّ ٱللَّهَ يَعۡلَمُ مَا فِىٓ أَنفُسِكُمۡ فَٱحۡذَرُوهُ‌ۚ وَٱعۡلَمُوٓاْ أَنَّ ٱللَّهَ غَفُورٌ حَلِيمٌ۬ (سورة البقرة 2:235)",
      "hindi": "और जानो कि अल्लाह आपके अंदर क्या है, तो उससे सावधान रहो। और जानो कि अल्लाह बख्शनेवाला और धैर्यशील है। (सूरह अल-बकारा 2:235)",
    },
  },
  {
    "index": 19,
    "name": "Al-Alim",
    "meaning": "The All-Knowing",
    "banglaName": "আল-আলীম",
    "banglaMeaning": "সর্বজ্ঞ",
    "arabicName": "ٱلۡعَلِيمُ",
    "arabicMeaning": "العليم",
    "hindiName": "अल-आलिम",
    "hindiMeaning": "सर्वज्ञ",
    "description": {
      "english": "Allah is the All-Knowing, the Omniscient.",
      "bangla": "আল্লাহ সর্বজ্ঞ, সকল জানতে পারেন।",
      "arabic": "ٱللَّهُ ٱلۡعَلِيمُ",
      "hindi": "अल्लाह सर्वज्ञ, सबकुछ जानने वाले हैं।",
    },
    "quranAyat": {
      "english": "And to Allah belongs the east and the west. So wherever you [might] turn, there is the Face of Allah. Indeed, Allah is all-Encompassing and Knowing. (Surah Al-Baqarah 2:115)",
      "bangla": "এবং পূর্ব ও পশ্চিম দিক আল্লাহর জন্য। সুতরাং আপনি যেখানেই [মুখ ফিরিয়ে] হোন, সেখানে আল্লাহর মুখ রয়েছে। নিশ্চয়, আল্লাহ সব সম্মোহক এবং সর্বজ্ঞ। (সূরা আল-বাকারা ২:১১৫)",
      "arabic": "وَلِلَّهِ ٱلۡمَشۡرِقُ وَٱلۡمَغۡرِبُ‌ۚ فَأَيۡنَمَا تُوَلُّواْ فَثَمَّ وَجۡهُ ٱللَّهِ‌ۚ إِنَّ ٱللَّهَ وَٲسِعٌ عَلِيمٌ۬ (سورة البقرة 2:115)",
      "hindi": "और पूर्व और पश्चिम की ओर अल्लाह का है। तो आप जहाँ भी मुड़ें, वहाँ अल्लाह का चेहरा है। निश्चय ही, अल्लाह हर जगह व्यापक और सबकुछ जानने वाले हैं। (सूरह अल-बकारा 2:115)",
    },
  },
  {
    "index": 20,
    "name": "Al-Qabid",
    "meaning": "The Constrictor",
    "banglaName": "আল-কাবিদ",
    "banglaMeaning": "সংকোচক",
    "arabicName": "ٱلۡقَابِضُ",
    "arabicMeaning": "القابض",
    "hindiName": "अल-काबिद",
    "hindiMeaning": "संकोचक",
    "description": {
      "english": "Allah is the Constrictor, the Straitener.",
      "bangla": "আল্লাহ সংকোচক, সম্মোহক।",
      "arabic": "ٱللَّهُ ٱلۡقَابِضُ",
      "hindi": "अल्लाह संकोचक, सम्मोहक हैं।",
    },
    "quranAyat": {
      "english": "And it is Allah who withholds the heavens from falling upon the earth except by His permission. Indeed Allah, to the people, is Kind and Merciful. (Surah Al-Haj 22:65)",
      "bangla": "আর আল্লাহ তার অনুমতি ছাড়াই আকাশকে পৃথিবীর উপর পড়ানোর থেকে রোকে। নিশ্চয় আল্লাহ মানুষের প্রতি দয়ালু এবং দয়ালু। (সূরা আল-হাজ ২২:৬৫)",
      "arabic": "وَهُوَ ٱلَّذِى يَمۡسَكُ ٱلسَّمَآءَ أَن تَقَعَ عَلَى ٱلۡأَرۡضِ إِلَّا بِإِذۡنِهِۦۤ‌ۚ إِنَّ ٱللَّهَ بِٱلنَّاسِ لَرَءُوفٌ۬ رَّحِيمٌ۬ (سورة الحج 22:65)",
      "hindi": "और यह अल्लाह है जो अपनी अनुमति के बिना आकाश को पृथ्वी पर गिरने से रोकता है। बेशक अल्लाह मानवता के प्रति दयालु और दयालु हैं। (सूरह अल-हज 22:65)",
    },
  },
  {
    "index": 21,
    "name": "Al-Basit",
    "meaning": "The Expander",
    "banglaName": "আল-বাসিত",
    "banglaMeaning": "বহুরূপী",
    "arabicName": "ٱلۡبَاسِطُ",
    "arabicMeaning": "الباسط",
    "hindiName": "अल-बासित",
    "hindiMeaning": "बहुरूपी",
    "description": {
      "english": "Allah is the Expander, the Munificent.",
      "bangla": "আল্লাহ বহুরূপী, দাতা।",
      "arabic": "ٱللَّهُ ٱلۡبَاسِطُ",
      "hindi": "अल्लाह बहुरूपी, दाता हैं।",
    },
    "quranAyat": {
      "english": "Did We not expand for you, [O Muhammad], your breast? (Surah Ash-Sharh 94:1)",
      "bangla": "আমি তোমার জন্য তোমার ছাতি বড় করিনি কি? (সূরা আশ-শর্হ ৯৪:১)",
      "arabic": "أَلَمۡ نَشۡرَحۡ لَكَ صَدۡرَكَ (سورة الشرح 94:1)",
      "hindi": "क्या हमने तुम्हारे लिए तुम्हारे सीने को नहीं फैलाया? (सूरह अश-शरह 94:1)",
    },
  },
  {
    "index": 22,
    "name": "Al-Khafid",
    "meaning": "The Abaser",
    "banglaName": "আল-খাফিদ",
    "banglaMeaning": "অহংকারী",
    "arabicName": "ٱلۡخَافِضُ",
    "arabicMeaning": "الخافض",
    "hindiName": "अल-ख़ाफ़िद",
    "hindiMeaning": "अहंकारी",
    "description": {
      "english": "Allah is the Abaser, the Humbler.",
      "bangla": "আল্লাহ অহংকারী, অধমানকরণকারী।",
      "arabic": "ٱللَّهُ ٱلۡخَافِضُ",
      "hindi": "अल्लाह अहंकारी, नीच करनेवाला हैं।",
    },
    "quranAyat": {
      "english": "And thus We have tried some of them through others that the disbelievers might say, 'Is it these whom Allah has favored among us?' Is not Allah most knowing of those who are grateful? (Surah Al-Ankabut 29:6)",
      "bangla": "এবং আমি একে অপরের মাধ্যমে কয়েকজন লোকের পরীক্ষা করেছি, যাতে অবিশ্বাসীরা বলতে পারে, 'কি আল্লাহ এই মধ্যে সংগ্রামীদের উপকার করেছেন?' কি আল্লাহ আপনাদের মধ্যে কৃতজ্ঞ লোকগণের বিষয়ে সর্বজ্ঞ না? (সূরা আল-আনকাবুত ২৯:৬)",
      "arabic": "وَلَقَدۡ فَتَنَّا ٱلَّذِينَ مِن قَبۡلِهِمۡ‌ۖ فَلَيَعۡلَمَنَّ ٱللَّهُ ٱلَّذِينَ صَدَقُواْ وَلَيَعۡلَمَنَّ ٱلۡكَـٰذِبِينَ (سورة العنكبوت 29:6)",
      "hindi": "और हमने इनकी परीक्षा की है, कि कुछ लोगों को अन्य लोगों से, ताकि काफिर लोग कह सकें, 'क्या इन्हें ही अल्लाह ने हम में से अनुग्रहित किया है?' क्या अल्लाह आभारी लोगों को नहीं जानते? (सूरह अल-अंक़बूत 29:6)",
    },
  },
  {
    "index": 23,
    "name": "Ar-Rafi",
    "meaning": "The Exalter",
    "banglaName": "আর-রাফিউ",
    "banglaMeaning": "উচ্চতার",
    "arabicName": "ٱلۡرَّافِعُ",
    "arabicMeaning": "الرافع",
    "hindiName": "अर-राफ़ि",
    "hindiMeaning": "उच्चताकर्ता",
    "description": {
      "english": "Allah is the Exalter, the Elevator.",
      "bangla": "আল্লাহ উচ্চতার, উচ্চ করণার।",
      "arabic": "ٱللَّهُ ٱلۡرَّافِعُ",
      "hindi": "अल्लाह उच्चताकर्ता, उठानेवाला हैं।",
    },
    "quranAyat": {
      "english": "So do not assert yourselves; He is most knowing of who fears Him. (Surah An-Najm 53:32)",
      "bangla": "তাহলে নিজেদের অধিকার কোনোভাবে করিবেন না; তিনি সবচেয়ে ভীতিপ্রদ সেই লোকগণের প্রতি সর্বজ্ঞ। (সূরা আন-নাজম ৫৩:৩২)",
      "arabic": "فَلَا تُزَكُّوٓاْ أَنفُسَكُمۡ‌ۖ هُوَ أَعۡلَمُ بِمَنِ ٱتَّقَىٰ (سورة النجم 53:32)",
      "hindi": "तो अपने आप को महत्वाकांक्षा मत करो; वह सबसे अधिक डरने वाले को सबसे अधिक जानता है। (सूरह अन-नज्म 53:32)",
    },
  },
  {
    "index": 24,
    "name": "Al-Mu'izz",
    "meaning": "The Bestower of Honors",
    "banglaName": "আল-মুইজ্জ",
    "banglaMeaning": "মর্যাদাযুক্ত",
    "arabicName": "ٱلۡمُعِزُّ",
    "arabicMeaning": "المعز",
    "hindiName": "अल-मुइज़्ज़",
    "hindiMeaning": "सम्मान प्रदानकर्ता",
    "description": {
      "english": "Allah is the Bestower of Honors, the Giver of Dignity.",
      "bangla": "আল্লাহ মর্যাদাযুক্ত, গর্বিত উপহারকারী।",
      "arabic": "ٱللَّهُ ٱلۡمُعِزُّ",
      "hindi": "अल्लाह सम्मान प्रदानकर्ता, गर्वयुक्त देनेवाला हैं।",
    },
    "quranAyat": {
      "english": "And be not like those who say, 'We have heard,' while they do not hear. (Surah Al-Anfal 8:21)",
      "bangla": "আর সেই লোকের মত হিসেবে না হোন যারা বলে, 'আমরা শুনেছি', তবে তারা শুনে না। (সূরা আল-আনফাল ৮:২১)",
      "arabic": "وَلَا تَكُونُواْ كَٱلَّذِينَ يَقُولُونَ سَمِعۡنَا وَهُمۡ لَا يَسۡمَعُونَ (سورة الأنفال 8:21)",
      "hindi": "और वह लोगों की तरह ना बनें जो कहते हैं, 'हमने सुना है', जबकि वे सुनते नहीं। (सूरह अल-अंफाल 8:21)",
    },
  },
  {
    "index": 25,
    "name": "Al-Mudhill",
    "meaning": "The Dishonorer",
    "banglaName": "আল-মুদ্ধিল",
    "banglaMeaning": "অপমানকরণকারী",
    "arabicName": "ٱلۡمُذِلُّ",
    "arabicMeaning": "المذل",
    "hindiName": "अल-मुद्धिल",
    "hindiMeaning": "अपमानकर्ता",
    "description": {
      "english": "Allah is the Dishonorer, the Humiliator.",
      "bangla": "আল্লাহ অপমানকরণকারী, অপমানকরণকারী।",
      "arabic": "ٱللَّهُ ٱلۡمُذِلُّ",
      "hindi": "अल्लाह अपमानकर्ता, अपमानकर्ता हैं।",
    },
    "quranAyat": {
      "english": "Indeed, the worst of living creatures in the sight of Allah are the deaf and dumb who do not use reason. (Surah Al-Anfal 8:22)",
      "bangla": "নিশ্চয়ই, অল্পবুদ্ধিমান আবার বহিষ্কৃত জীব। যারা বুদ্ধি ব্যবহার করে না। (সূরা আল-আনফাল ৮:২২)",
      "arabic": "إِنَّ شَرَّ ٱلدَّوَآبِّ عِندَ ٱللَّهِ ٱلصُّمُّ ٱلۡبُكۡمُ ٱلَّذِينَ لَا يَعۡقِلُونَ (سورة الأنفال 8:22)",
      "hindi": "बेशक अल्लाह की नजर में सबसे खराब जीवों में वह बहरे और गूंगे हैं जो तर्क का उपयोग नहीं करते। (सूरह अल-अंफाल 8:22)",
    },
  },
  {
    "index": 26,
    "name": "As-Sami",
    "meaning": "The All-Hearing",
    "banglaName": "আস-সামী",
    "banglaMeaning": "সর্বশ্রুতিমান",
    "arabicName": "ٱلسَّمِيعُ",
    "arabicMeaning": "السميع",
    "hindiName": "अस-सामी",
    "hindiMeaning": "सर्वश्रोता",
    "description": {
      "english": "Allah is the All-Hearing, the Hearer of All.",
      "bangla": "আল্লাহ সর্বশ্রুতিমান, সব শ্রুতিমান।",
      "arabic": "ٱللَّهُ ٱلسَّمِيعُ",
      "hindi": "अल्लाह सर्वश्रोता, सभी को सुननेवाला हैं।",
    },
    "quranAyat": {
      "english": "Indeed, Allah is Hearing and Seeing. (Surah Al-Mujadila 58:1)",
      "bangla": "নিশ্চয়ই, আল্লাহ শুনেন এবং দেখছেন। (সূরা আল-মুজাদিলা ৫৮:১)",
      "arabic": "قَدۡ سَمِعَ ٱللَّهُ قَوۡلَ ٱلَّتِى تُجَـٰدِلُكَ فِى زَوۡجِهَا وَتَشۡتَكِىٓ إِلَى ٱللَّهِ‌ۚ وَٱللَّهُ يَسۡمَعُ تَحَاوُرَكُمَآ‌ۚ إِنَّ ٱللَّهَ سَمِيعٌ۬ۤ بَصِيرٌ (سورة المجادلة 58:1)",
      "hindi": "बेशक, अल्लाह सुनते हैं और देखते हैं। (सूरह अल-मुजादिला 58:1)",
    },
  },
  {
    "index": 27,
    "name": "Al-Basir",
    "meaning": "The All-Seeing",
    "banglaName": "আল-বাসির",
    "banglaMeaning": "সর্বদৃষ্টিমান",
    "arabicName": "ٱلۡبَصِيرُ",
    "arabicMeaning": "البصير",
    "hindiName": "अल-बासिर",
    "hindiMeaning": "सर्वदर्शी",
    "description": {
      "english": "Allah is the All-Seeing, the Seer of All.",
      "bangla": "আল্লাহ সর্বদৃষ্টিমান, সব দেখনেও।",
      "arabic": "ٱللَّهُ ٱلۡبَصِيرُ",
      "hindi": "अल्लाह सर्वदर्शी, सब को देखनेवाला हैं।",
    },
    "quranAyat": {
      "english": "Or do you think that most of them hear or reason? They are not except like livestock. Rather, they are [even] more astray in [their] way. (Surah Al-Furqan 25:44)",
      "bangla": "তাদের অধিকাংশ শ্রবণ করে কিংবা চিন্তা করে? তারা কেবল পশুর মত, বরং তারা প্রচুর আত্মপ্রকাশে। (সূরা আল-ফুরকান ২৫:৪৪)",
      "arabic": "أَمۡ تَحۡسَبُ أَنَّ أَكۡثَرَهُمۡ يَسۡمَعُونَ أَوۡ يَعۡقِلُونَ‌ۚ إِنۡ هُمۡ إِلَّا كَٱلۡأَنۡعَـٰمِ‌ۖ بَلۡ هُمۡ أَضَلُّ سَبِيلً۬ا (سورة الفرقان 25:44)",
      "hindi": "क्या तुम सोचते हो कि उनमें से अधिकांश कान सुनते हैं या तर्क करते हैं? वे केवल पशु की तरह हैं, बल्कि वे अपने रास्ते में बहुत गुमराह हैं। (सूरह अल-फुर्कान 25:44)",
    },
  },
  {
    "index": 28,
    "name": "Al-Hakam",
    "meaning": "The Judge",
    "banglaName": "আল-হাকাম",
    "banglaMeaning": "ন্যায়কারী",
    "arabicName": "ٱلۡحَكَمُ",
    "arabicMeaning": "الحكم",
    "hindiName": "अल-हकम",
    "hindiMeaning": "न्यायाधीश",
    "description": {
      "english": "Allah is the Judge, the Arbitrator.",
      "bangla": "আল্লাহ ন্যায়কারী, সালিস।",
      "arabic": "ٱللَّهُ ٱلۡحَكَمُ",
      "hindi": "अल्लाह न्यायाधीश, अर्बिट्रेटर हैं।",
    },
    "quranAyat": {
      "english": "Indeed, Allah orders justice and good conduct and giving to relatives and forbids immorality and bad conduct and oppression. He admonishes you that perhaps you will be reminded. (Surah An-Nahl 16:90)",
      "bangla": "নিশ্চয়ই, আল্লাহ ন্যায় করা ও ভাল আচরণের অনুসারণ করেন, আত্মীয়দের মধ্যে দান করার আদেশ দেন এবং অপব্যবহার এবং ক্ষমতাপ্রদকরণের শিকারকরণ করেন। তিনি আপনাদের পরামর্শ দেন যাতে সম্ভবত আপনাদের পরামর্শ করা যায়। (সূরা আন-নাহল ১৬:৯০)",
      "arabic": "إِنَّ ٱللَّهَ يَأۡمُرُ بِٱلۡعَدۡلِ وَٱلۡإِحۡسَـٰنِ وَإِيتَآءِ ذِى ٱلۡقُرۡبَىٰ وَيَنۡهَىٰ عَنِ ٱلۡفَحۡشَآءِ وَٱلۡمُنكَرِ وَٱلۡبَغۡىِ‌ۚ يَعِظُكُمۡ لَعَلَّكُمۡ تَذَكَّرُونَ (سورة النحل 16:90)",
      "hindi": "बेशक, अल्लाह न्याय और अच्छे आचरण का आदेश देते हैं और रिश्तेदारों को देने और अनैतिकता और बुरे आचरण और अत्याचार से रोकते हैं। वह आपको धिक्कारते हैं कि शायद आप याद कर लें। (सूरह अन-नहल 16:90)",
    },
  },
  {
    "index": 29,
    "name": "Al-Adl",
    "meaning": "The Just",
    "banglaName": "আল-আদল",
    "banglaMeaning": "ন্যায়বিচারকারী",
    "arabicName": "ٱلۡعَدۡلُ",
    "arabicMeaning": "العدل",
    "hindiName": "अल-आदिल",
    "hindiMeaning": "न्यायविचारी",
    "description": {
      "english": "Allah is the Just, the Equitable.",
      "bangla": "আল্লাহ ন্যায়বিচারকারী, সমতুল্য।",
      "arabic": "ٱللَّهُ ٱلۡعَدۡلُ",
      "hindi": "अल्लाह न्यायविचारी, समान।",
    },
    "quranAyat": {
      "english": "Indeed, Allah does not do injustice, [even] as much as an atom's weight; while if there is a good deed, He multiplies it and gives from Himself a great reward. (Surah An-Nisa 4:40)",
      "bangla": "নিশ্চয়ই, অল্লাহ অন্যায় করেন না, একটি পরমাণুর ওজনের মতো; তবে যদি একটি ভাল কাজ থাকে, তিনি এটি বর্ধন করে এবং নিজ দিক থেকে বড় পুরস্কার দেন। (সূরা আন-নিসা ৪:৪০)",
      "arabic": "إِنَّ ٱللَّهَ لَا يَظۡلِمُ مِثۡقَالَ ذَرَّةٍ۬‌ۖ وَإِن تَكُ حَسَنَةٌ۬ يُضَـٰعِفۡهَا وَيُؤۡتِ مِن لَّدُنۡهُ أَجۡرًا عَظِيمً۬ا (سورة النساء 4:40)",
      "hindi": "बेशक, अल्लाह कोई अन्याय नहीं करता, एक परमाणु के वजन के बराबर; जबकि अगर कोई अच्छा काम हो, तो उसे वह बढ़ाता है और उससे बड़ा पुरस्कार देता है। (सूरह अन-निसा 4:40)",
    },
  },
  {
    "index": 30,
    "name": "Al-Latif",
    "meaning": "The Subtle One",
    "banglaName": "আল-লাতিফ",
    "banglaMeaning": "সুক্ষ্মতার",
    "arabicName": "ٱلۡلَّطِيفُ",
    "arabicMeaning": "اللطيف",
    "hindiName": "अल-लटीफ़",
    "hindiMeaning": "सूक्ष्म",
    "description": {
      "english": "Allah is the Subtle One, the Gracious, the Kind.",
      "bangla": "আল্লাহ সুক্ষ্মতার, মেহেরবান, দয়ালু।",
      "arabic": "ٱللَّهُ ٱلَّطِيفُ",
      "hindi": "अल्लाह सूक्ष्म, दयालु, कृपालु हैं।",
    },
    "quranAyat": {
      "english": "For Allah is full of kindness to those who believe. (Surah Al-Baqarah 2:143)",
      "bangla": "আল্লাহ বিশ্বাসীদের প্রতি অনেক দয়ালু। (সূরা আল-বাক্বারাহ ২:১৪৩)",
      "arabic": "وَكَانَ ٱللَّهُ بِٱلۡمُؤۡمِنِينَ رَحِيمً۬ا (سورة البقرة 2:143)",
      "hindi": "क्योंकि अल्लाह विश्वासी लोगों के प्रति दयालु हैं। (सूरह अल-बकराह 2:143)",
    },
  },
  {
    "index": 31,
    "name": "Al-Khabir",
    "meaning": "The Aware",
    "banglaName": "আল-খবীর",
    "banglaMeaning": "জান্তা",
    "arabicName": "ٱلۡخَبِيرُ",
    "arabicMeaning": "الخبير",
    "hindiName": "अल-खबीर",
    "hindiMeaning": "जाननेवाला",
    "description": {
      "english": "Allah is the Aware, the All-Acquainted.",
      "bangla": "আল্লাহ জান্তা, সবকিছু জানেন।",
      "arabic": "ٱللَّهُ ٱلۡخَبِيرُ",
      "hindi": "अल्लाह जाननेवाला, सभी अवगत हैं।",
    },
    "quranAyat": {
      "english": "And sufficient is Allah as a Witness between us and you, and He is the Forgiving, the Merciful. (Surah Al-Anfal 8:64)",
      "bangla": "আমাদের ও আপনাদের মধ্যে আল্লাহ যথার্থ প্রমাণ হিসাবে যথেষ্ট, এবং তিনি ক্ষমাশীল, দয়ালু। (সূরা আল-আনফাল ৮:৬৪)",
      "arabic": "وَكَفَىٰ بِٱللَّهِ شَهِيدً۬ا بَيۡنَنَا وَبَيۡنَكُمۡ‌ۚ وَهُوَ ٱلۡغَفُورُ ٱلرَّحِيمُ (سورة الأنفال 8:64)",
      "hindi": "और अल्लाह हमारे और आपके बीच गवाह के रूप में पर्याप्त हैं, और वह छूट देने वाला, दयालु हैं। (सूरह अल-अंफाल 8:64)",
    },
  },
  {
    "index": 32,
    "name": "Al-Halim",
    "meaning": "The Forbearing",
    "banglaName": "আল-হালিম",
    "banglaMeaning": "ধৈর্যশীল",
    "arabicName": "ٱلۡحَلِيمُ",
    "arabicMeaning": "الحليم",
    "hindiName": "अल-हलीम",
    "hindiMeaning": "धैर्यशील",
    "description": {
      "english": "Allah is the Forbearing, the Indulgent.",
      "bangla": "আল্লাহ ধৈর্যশীল, উপভোগী।",
      "arabic": "ٱللَّهُ ٱلۡحَلِيمُ",
      "hindi": "अल्लाह धैर्यशील, उपभोगशील हैं।",
    },
    "quranAyat": {
      "english": "And if Allah were to impose blame on the people for what they have earned, He would not leave upon the earth any creature. But He defers them for a specified term. And when their time comes, then indeed Allah has ever been, of His servants, Seeing. (Surah Fatir 35:45)",
      "bangla": "যদি আল্লাহ মানুষদের যা তারা অর্জন করেছে তার জন্য দোষী ঘোষণা করেন, তবে তিনি পৃথিবীর উপর কোনো জীবনী বাঁচাতেন না। তিনি তাদের নির্ধারিত সময়ের জন্য বিলম্বিত করেন। এবং যখন তাদের সময় পৌঁছায়, তবে নিশ্চয়ই আল্লাহ তার কর্মকর্তাদের উপর সবসময় দেখতে আসেন। (সূরা ফাতির ৩৫:৪৫)",
      "arabic": "وَلَوۡ يُؤَاخِذُ ٱللَّهُ ٱلنَّاسَ بِمَا ڪَسَبُواْ مَا تَرَكَ عَلَىٰ ظَهۡرِهَا مِن دَآبَّةٍ۬ وَلَـٰكِن يُؤَخِّرُهُمۡ إِلَىٰٓ أَجَلٍ۬ مُّسَمًّ۬ىۖ فَإِذَا جَآءَ أَجَلُهُمۡ فَإِنَّ ٱللَّهَ كَانَ بِعِبَادِهِۦ بَصِيرً۬ا (سورة فاطر 35:45)",
      "hindi": "और अगर अल्लाह मनुष्यों को उसके वारंवार के लिए दोषी ठहराये तो वह पृथ्वी पर कोई जीव नहीं छोड़ेगा। लेकिन उन्हें निश्चित समय के लिए स्थानांतरित कर देता है। और जब उनका समय आएगा, तो निश्चय ही अल्लाह अपने बन्दों के साथ सब कुछ देख रहा है। (सूरह फातिर 35:45)",
    },
  },
  {
    "index": 33,
    "name": "Al-Azim",
    "meaning": "The Great One",
    "banglaName": "আল-আজিম",
    "banglaMeaning": "মহান",
    "arabicName": "ٱلۡعَظِيمُ",
    "arabicMeaning": "العظيم",
    "hindiName": "अल-अजीम",
    "hindiMeaning": "महान",
    "description": {
      "english": "Allah is the Great One, the Magnificent.",
      "bangla": "আল্লাহ মহান, আलোকিত।",
      "arabic": "ٱللَّهُ ٱلۡعَظِيمُ",
      "hindi": "अल्लाह महान, विशাল।",
    },
    "quranAyat": {
      "english": "The command of Allah is coming, so be not impatient for it. Exalted is He and high above what they associate with Him. (Surah An-Nahl 16:1)",
      "bangla": "আল্লাহর আদেশ আসছে, তাই তুমি এর প্রতি অধীর হও না। তিনি উচ্চতর, এবং তারা তার সাথে যা যুক্ত করেছে তার থেকে উঁচু। (সূরা আন-নাহল ১৬:১)",
      "arabic": "أَتَىٰٓ أَمۡرُ ٱللَّهِ فَلَا تَسۡتَعۡجِلُوهُ‌ۚ سُبۡحَـٰنَهُۥ وَتَعَـٰلَىٰ عَمَّا يُشۡرِكُونَ (سورة النحل 16:1)",
      "hindi": "अल्लाह का हुक्म आ रहा है, इसलिए इसके प्रति अधीर न हो। वह पवित्र है और उनके साथ जो वे उसके साथ जोड़ते हैं से उच्च है। (सूरह अन-नहल 16:1)",
    },
  },
  {
    "index": 34,
    "name": "Al-Ghaffar",
    "meaning": "The All-Forgiving",
    "banglaName": "আল-গফফার",
    "banglaMeaning": "সর্বক্ষম",
    "arabicName": "ٱلۡغَفَّارُ",
    "arabicMeaning": "الغفار",
    "hindiName": "अल-गफ़्फार",
    "hindiMeaning": "सबक्षम",
    "description": {
      "english": "Allah is the All-Forgiving, the Absolver of Sins.",
      "bangla": "আল্লাহ সর্বক্ষম, পাপক্ষমণ।",
      "arabic": "ٱللَّهُ ٱلۡغَفَّارُ",
      "hindi": "अल्लाह सबक्षम, पापक्षमण हैं।",
    },
    "quranAyat": {
      "english": "Say, \"O My servants who have transgressed against themselves [by sinning], do not despair of the mercy of Allah. Indeed, Allah forgives all sins. Indeed, it is He who is the Forgiving, the Merciful.\" (Surah Az-Zumar 39:53)",
      "bangla": "বলুন, \"হে আমার বান্দাগণ, যারা তাদের নিজেদের বিপর্যস্ত করেছে (অপরাধের মাধ্যমে), আল্লাহর রহমতে আশা নিক্ষেপ করো না। নিশ্চয়ই, আল্লাহ সব পাপ ক্ষমা করেন। নিশ্চয়ই, তিনি যাতে ক্ষমাশীল, দয়ালু।\" (সূরা আয-যুমার ৩৯:৫৩)",
      "arabic": "قُلۡ يَـٰعِبَادِىَ ٱلَّذِينَ أَسۡرَفُواْ عَلَىٰٓ أَنفُسِهِمۡ لَا تَقۡنَطُواْ مِن رَّحۡمَةِ ٱللَّهِ‌ۚ إِنَّ ٱللَّهَ يَغۡفِرُ ٱلذُّنُوبَ جَمِيعًا‌ۚ إِنَّهُ ۥ هُوَ ٱلۡغَفُورُ ٱلرَّحِيمُ (سورة الزمر 39:53)",
      "hindi": "कहो, \"हे मेरे दासों, जिन्होंने अपने आप को (पाप करके) अत्यधिक दुर्बल किया है, अल्लाह की रहमत से निराश न हो। बेशक, अल्लाह सभी पापों को माफ़ करता है। निश्चय ही वह क्षमाशील, दयालु हैं।\" (सूरह अज-जुमर 39:53)",
    },
  },
  {
    "index": 35,
    "name": "Al-Shakur",
    "meaning": "The Appreciative",
    "banglaName": "আল-শাকুর",
    "banglaMeaning": "সম্মান করিতে",
    "arabicName": "ٱلشَّكُورُ",
    "arabicMeaning": "الشكور",
    "hindiName": "अल-शाकिर",
    "hindiMeaning": "प्रशंसक",
    "description": {
      "english": "Allah is the Appreciative, the Grateful.",
      "bangla": "আল্লাহ সম্মান করিতে, কৃতজ্ঞ।",
      "arabic": "ٱللَّهُ ٱلشَّكُورُ",
      "hindi": "अल्लाह प्रशंसक, आभारी हैं।",
    },
    "quranAyat": {
      "english": "And whoever does righteous deeds, whether male or female, while being a believer - those will enter Paradise and will not be wronged, [even as much as] the speck on a date seed. (Surah An-Nisa 4:124)",
      "bangla": "এবং যে কেউ ভাল কর্ম করে, নারী হোক না পুরুষ, এবং বিশ্বাসী হোক - তারা স্বর্গে ঢুকবে এবং অন্যায় করা হবে না, [এমন পরিমাণে যত খেজুরের বীজের ক্ষুদ্রতম অংশও। (সূরা আন-নিসা ৪:১২৪)",
      "arabic": "وَمَن يَعۡمَلۡ مِنَ ٱلصَّـٰلِحَـٰتِ مِن ذَكَرٍ۬ أَوۡ أُنثَىٰ وَهُوَ مُؤۡمِنٌ۬ فَأُوْلَـٰٓٮِٕكَ يَدۡخُلُونَ ٱلۡجَنَّةَ وَلَا يُظۡلَمُونَ نَقِيرً۬ا (سورة النساء 4:124)",
      "hindi": "और जो कोई भी अच्छे काम करता है, चाहे पुरुष हो या स्त्री, और वह विश्वासी हो - वे स्वर्ग में प्रवेश करेंगे और किसी तरह का अन्याय नहीं होगा, [खजूर के बीज के] सूजी पर भी नहीं। (सूरह अन-निसा 4:124)",
    },
  },
  {
    "index": 36,
    "name": "Al-Ali",
    "meaning": "The Highest",
    "banglaName": "আল-আলী",
    "banglaMeaning": "উচ্চ",
    "arabicName": "ٱلۡعَلِىُّ",
    "arabicMeaning": "العلي",
    "hindiName": "अल-अली",
    "hindiMeaning": "उच्च",
    "description": {
      "english": "Allah is the Highest, the Most Exalted.",
      "bangla": "আল্লাহ উচ্চ, সর্বোচ্চ।",
      "arabic": "ٱللَّهُ ٱلۡعَلِىُّ",
      "hindi": "अल्लाह उच्च, सर्वोच्च हैं।",
    },
    "quranAyat": {
      "english": "Exalted is Allah, the True Sovereign. There is no deity except Him, Lord of the Noble Throne. (Surah Al-Muminun 23:116)",
      "bangla": "সুতরাং আল্লাহর নাম প্রশংসিত, সত্য রাজা। তার বাদশাহীর সিপাহীর বাহিনীতে একমাত্র ঈশ্বর তিনি, মহান সিংহাসনের প্রভু। (সূরা আল-মুমিনূন ২৩:১১৬)",
      "arabic": "تَعَـٰلَى ٱللَّهُ ٱلۡمَلِكُ ٱلۡحَقُّ‌ۖ لَآ إِلَـٰهَ إِلَّا هُوَ رَبُّ ٱلۡعَرۡشِ ٱلۡكَرِيمِ (سورة المؤمنون 23:116)",
      "hindi": "उच्च है अल्लाह, सच्चा शासक। उसके सिवा कोई देवता नहीं है, बाग़ी सिंहासन के स्वामी। (सूरह अल-मुमिनून 23:116)",
    },
  },{
    "index": 37,
    "name": "Al-Kabir",
    "meaning": "The Greatest",
    "banglaName": "আল-কাবির",
    "banglaMeaning": "সর্বোচ্চ",
    "arabicName": "ٱلۡكَبِيرُ",
    "arabicMeaning": "الكبير",
    "hindiName": "अल-कबीर",
    "hindiMeaning": "सर्वोत्तम",
    "description": {
      "english": "Allah is the Greatest, the Most Great.",
      "bangla": "আল্লাহ সর্বোচ্চ, সবচেয়ে বড়।",
      "arabic": "ٱللَّهُ ٱلۡكَبِيرُ",
      "hindi": "अल्लाह सर्वोत्तम, सबसे महान हैं।"
    },
    "quranAyat": {
      "english": "Allah - there is no deity except Him, the Ever-Living, the Sustainer of [all] existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is [presently happening] before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great. (Surah Al-Baqarah 2:255)",
      "bangla": "আল্লাহ সম্পূর্ণ প্রাণীতে সৃষ্টি করার স্থিতিশীল, প্রাণীগুলোর ভালবাসা ও তার সম্মানের মধ্যে মাত্র আল্লাহের প্রাপ্তি হয়। তিনি সমগ্র বিশ্বের পরিচ্ছন্নতা এবং শক্তির উপাদান নিয়েন। তার আগে এবং তার পর ঘটানো হচ্ছে সবকিছু তিনি সমগ্র প্রজাতির সৃষ্টি করেছেন। তার থেকে কিছুই লুকিয়ে থাকতে পারে না, যে কেবল তার ইচ্ছার মোতাবেক হয়। আর তার কুরশী আকাশ ও পৃথিবীর উপর ছড়িয়ে ছিটিয়ে আছে, এবং এগুলির রক্ষা তাকে কোন কাজে ঝুঁকিতে অব্যাহত করে না। তিনি সর্বোচ্চ, সর্বশ্রেষ্ঠ। (সূরা আল-বাক্বারাহ ২:২৫৫)",
      "arabic": "ٱللَّهُ لَآ إِلَـٰهَ إِلَّا هُوَ ٱلۡحَىُّ ٱلۡقَيُّومُ‌ۚ لَا تَأۡخُذُهُ ۥ سِنَةٌ۬ وَلَا نَوۡمٌ۬‌ۚ لَّهُ ۥ مَا فِى ٱلسَّمَـٰوَٲتِ وَمَا فِى ٱلۡأَرۡضِ‌ۗ مَن ذَا ٱلَّذِى يَشۡفَعُ عِندَهُ ۥۤ إِلَّا بِإِذۡنِهِۦ‌ۚ يَعۡلَمُ مَا بَيۡنَ أَيۡدِيهِمۡ وَمَا خَلۡفَهُمۡ‌ۖ وَلَا يُحِيطُونَ بِشَىۡءٍ۬ مِّنۡ عِلۡمِهِۦۤ إِلَّا بِمَا شَآءَ‌ۚ وَسِعَ كُرۡسِيُّهُ ٱلسَّمَـٰوَٲتِ وَٱلۡأَرۡضَ‌ۖ وَلَا يَـُٔودُهُ ۥ حِفۡظُهُمَا‌ۚ وَهُوَ ٱلۡعَلِىُّ ٱلۡعَظِيمُ (سورة البقرة 2:255)",
      "hindi": "अल्लाह - उसके सिवा कोई देवता नहीं है, वह जीवनी, सम्पोषक [सब] अस्तित्व का संभालक है। न उसे नींद आती है और न उसे सोने की आवश्यकता है। उसका है जो कुछ भी आसमानों में है और जो कुछ भूमि में है। किस है जो उसके इजाजत के बिना उसके पास दलील कर सकता है? उसे पता है उनके सामने और उनके पीछे क्या है, और वे उसके ज्ञान का कुछ भी नहीं बाँध पाते, बस वही जो वह चाहता है। उसका कुर्सी आसमानों और धरती को आवरण करता है, और उनका संरक्षण उसे थका नहीं देता। और वह सर्वोच्च, सर्वोत्तम है। (सूरह अल-बकाराह 2:255)"
    }
  },
  {
    "index": 38,
    "name": "Al-Hafiz",
    "meaning": "The Guardian",
    "banglaName": "আল-হাফিজ",
    "banglaMeaning": "রক্ষক",
    "arabicName": "ٱلۡحَفِيظُ",
    "arabicMeaning": "الحفيظ",
    "hindiName": "अल-हाफिज़",
    "hindiMeaning": "संरक्षक",
    "description": {
      "english": "Allah is the Guardian, the Preserver.",
      "bangla": "আল্লাহ রক্ষক, রক্ষক।",
      "arabic": "ٱللَّهُ ٱلۡحَفِيظُ",
      "hindi": "अल्लाह संरक्षक, रक्षक हैं।"
    },
    "quranAyat": {
      "english": "Indeed, We have sent down to you the Book, [O Muhammad], in truth. So worship Allah, [being] sincere to Him in religion. Unquestionably, for Allah is the pure religion. And those who take protectors besides Him [say], \"We only worship them that they may bring us nearer to Allah in position.\" Indeed, Allah will judge between them concerning that over which they differ. Indeed, Allah does not guide he who is a liar and [confirmed] disbeliever. (Surah Az-Zumar 39:2-3)",
      "bangla": "নিশ্চয় আমি তোমার প্রতি সত্যে আমরা আসম্পূর্ণ রূপে আল্লাহকে প্রতিপূর্ণ বিশ্বাস করে পুস্তক অবতারিত করেছি। তাই ধর্মে সতীর্থক হওয়া আল্লাহর প্রতি সত্যে আল্লাহ ধর্ম। আর যারা তার বাদে সন্ত্রস্ত গ্রহণ করেছে তারা [বলে] \"আমরা এবার তারা প্রতি যাচাইয়ের উদ্দেশ্যে কেবল তারা যাচাইয়ের উদ্দেশ্যে আমরা তাদের পূজা করি যেন তারা আল্লাহ কে আমাদের সাথে বেঁধে নেওয়ার জন্য।\" নিশ্চয়ই, আল্লাহ তাদের মধ্যে যে বিবাদে তারা পার্থক্য করে তার সাথে মধ্যস্থতা করবেন। নিশ্চয়ই, আল্লাহ যে কোন মিথ্যেবাদী এবং [নিশ্চিত] কাফিরের পথ প্রদর্শন করে না। (সূরা আয-যুমার ৩৯:২-৩)",
      "arabic": "إِنَّآ أَنزَلۡنَآ إِلَيۡكَ ٱلۡكِتَـٰبَ بِٱلۡحَقِّ‌ۖ فَٱعۡبُدِ ٱللَّهَ مُخۡلِصً۬ا لَّهُ ٱلدِّينَ‌ۚ أَلَا لِلَّهِ ٱلدِّينُ ٱلۡخَالِصُ‌ۚ وَٱلَّذِينَ ٱتَّخَذُواْ مِن دُونِهِۦۤ أَوۡلِيَآءَ مَا نَعۡبُدُهُمۡ إِلَّا لِيُقَرِّبُونَآ إِلَى ٱللَّهِ زُلۡفَىٰٓ إِنَّ ٱللَّهَ يَحۡكُمُ بَيۡنَهُمۡ فِى مَا هُمۡ فِيهِ يَخۡتَلِفُونَ‌ۗ إِنَّ ٱللَّهَ لَا يَہۡدِى مَنۡ هُوَ كَـٰذِبٌ۬ كَفَّارٌ۬ (سورة الزمر 39:2-3)",
      "hindi": "वास्तव में, हमने तुम्हारे पास सच्चाई में पुस्तक [अर्थात्, या मुहम्मद], भेजी है। इसलिए अल्लाह की पूजा करो, [उसके प्रति] धर्म में संवेदनशील रहो। निःसंदेह, अल्लाह के लिए पवित्र धर्म है। और जो उसके बाहर रक्षक लेते हैं [कहते हैं], \"हम केवल उनकी पूजा करते हैं कि वे हमें अल्लाह के पास पद में अधिक करें।\" वास्तव में, अल्लाह उन लोगों के बीच जो वे अलग होते हैं उनके बीच फैसला करेगा। वास्तव में, अल्लाह उसकी मार्गदर्शिका नहीं करता है जो झूठा और [निश्चित] अविश्वासी है। (सूरह अज-जुमर 39:2-3)"
    }
  },
  {
    "index": 39,
    "name": "Al-Muqit",
    "meaning": "The Maintainer",
    "banglaName": "আল-মুকিত",
    "banglaMeaning": "পোষক",
    "arabicName": "ٱلۡمُقِيتُ",
    "arabicMeaning": "المقيت",
    "hindiName": "अल-मुकित",
    "hindiMeaning": "पोषक",
    "description": {
      "english": "Allah is the Maintainer, the Provider of Sustenance.",
      "bangla": "আল্লাহ পোষক, পোষক।",
      "arabic": "ٱللَّهُ ٱلۡمُقِيتُ",
      "hindi": "अल्लाह पोषक, पोषक हैं।"
    },
    "quranAyat": {
      "english": "And when adversity touches man, he calls upon Us; then when We bestow on him a favor from Us, he says, \"I have only been given it because of [my] knowledge.\" Rather, it is a trial, but most of them do not know. (Surah Az-Zumar 39:49)",
      "bangla": "যখন মানুষের উপদ্রব ঘটে তখন সে আমাদের প্রতিবাদ করে; তখন আমরা তার উপর একটি উপকার দিলে সে বলে, \"আমার এটি মাত্র [আমার] জ্ঞানের কারণে দেয়া হয়েছে।\" বরং, এটি একটি পরীক্ষা, তবে তাদের মেয়াদের অধিকাংশ জানে না। (সূরা আজ-যুমার ৩৯:৪৯)",
      "arabic": "وَإِذَا مَسَّ ٱلۡإِنسَـٰنَ ضُرٌّ۬ دَعَانَا لِجَنۢبِهِۦٓ أَوۡ قَاعِدًا أَوۡ قَآئِمً۬ا فَلَمَّا كَشَفۡنَا عَنۡهُ ضُرَّهُ ۥ مَرَّ ڪَأَن لَّمۡ يَدۡعُنَآ إِلَىٰ ضُرٍّ۬ مَّسَّهُ ۥ‌ۚ كَذَٲلِكَ زُيِّنَ لِلۡمُسۡرِفِينَ مَا كَانُواْ يَعۡمَلُونَ (سورة الزمر 39:49)",
      "hindi": "और जब किसी मनुष्य को कष्ट लगता है, तो वह हमें पुकारता है; फिर जब हम उस पर हमारी एक अनुग्रह देते हैं, तो वह कहता है, \"मुझे इसका केवल [मेरे] ज्ञान के कारण ही दिया गया है।\" बल्कि, यह एक परीक्षा है, लेकिन उनमें से अधिकांश नहीं जानते। (सूरह अज-जुमर 39:49)"
    }
  },
  {
    "index": 40,
    "name": "Al-Hasib",
    "meaning": "The Reckoner",
    "banglaName": "আল-হাসিব",
    "banglaMeaning": "হিসাবকর্তা",
    "arabicName": "ٱلۡحَسِيبُ",
    "arabicMeaning": "الحسيب",
    "hindiName": "अल-हासिब",
    "hindiMeaning": "बारह करनेवाला",
    "description": {
      "english": "Allah is the Reckoner, the Accounter.",
      "bangla": "আল্লাহ হিসাবকর্তা, হিসাবকর্তা।",
      "arabic": "ٱللَّهُ ٱلۡحَسِيبُ",
      "hindi": "अल्लाह बारह करनेवाला, हिसाबकर्ता हैं।"
    },
    "quranAyat": {
      "english": "Say, \"O My servants who have transgressed against themselves [by sinning], do not despair of the mercy of Allah. Indeed, Allah forgives all sins. Indeed, it is He who is the Forgiving, the Merciful.\" (Surah Az-Zumar 39:53)",
      "bangla": "বল, \"আমার কর্তৃবৃন্দ, যারা তাদের নিজেদের বিরুদ্ধে অতিক্রান্ত হয়েছে [পাপের মাধ্যমে], তাদের আল্লাহর ক্ষমার ব্যর্থ হতে দিবেন না। যতই পাপ হোক আল্লাহ সব পাপ ক্ষমা করে। সত্যিই, তিনি যিনি ক্ষমাশীল, দয়ালু।\" (সূরা আজ-যুমার 39:53)",
      "arabic": "قُلۡ يَـٰعِبَادِىَ ٱلَّذِينَ أَسۡرَفُواْ عَلَىٰٓ أَنفُسِهِمۡ لَا تَقۡنَطُواْ مِن رَّحۡمَةِ ٱللَّهِ‌ۚ إِنَّ ٱللَّهَ يَغۡفِرُ ٱلذُّنُوبَ جَمِيعًا‌ۚ إِنَّهُ ۥ هُوَ ٱلۡغَفُورُ ٱلرَّحِيمُ (سورة الزمر 39:53)",
      "hindi": "कहो, \"हे मेरे नौकर, जो अपने आप पर पाप किया है [अपने अपराध के द्वारा], उन्हें अल्लाह की रहमत से निराश न होने देना। वास्तव में, अल्लाह सभी पापों को क्षमा करता है। वास्तव में, वही है जो क्षमाशील, दयालु है।\" (सूरह अज-युमार 39:53)"
    }
  },{
    "index": 41,
    "name": "Al-Jalil",
    "meaning": "The Majestic",
    "banglaName": "আল-জালিল",
    "banglaMeaning": "মহান",
    "arabicName": "ٱلۡجَلِيلُ",
    "arabicMeaning": "الجليل",
    "hindiName": "अल-जलील",
    "hindiMeaning": "विशालकाय",
    "description": {
      "english": "Allah is the Majestic, the Grand.",
      "bangla": "আল্লাহ মহান, মহান।",
      "arabic": "ٱللَّهُ ٱلۡجَلِيلُ",
      "hindi": "अल्लाह विशालकाय, महान हैं।"
    },
    "quranAyat": {
      "english": "They fear their Lord above them, and they do what they are commanded. (Surah An-Nahl 16:50)",
      "bangla": "তারা তাদের উপরের তাদের প্রভু ভয় করে, এবং তারা যা নিয়মিত তাদের করা হয়। (সূরা আন-নাহল ১৬:৫০)",
      "arabic": "يَخَافُونَ رَبَّهُم مِّن فَوۡقِهِمۡ وَيَفۡعَلُونَ مَا يُؤۡمَرُونَ (سورة النحل 16:50)",
      "hindi": "वे अपने प्रभु से ऊपर से डरते हैं, और वे जो कुछ उन्हें आज्ञा दिया जाता है वह करते हैं। (सूरह अन-नहल 16:50)"
    }
  },
  {
    "index": 42,
    "name": "Al-Karim",
    "meaning": "The Generous",
    "banglaName": "আল-কারিম",
    "banglaMeaning": "উদার",
    "arabicName": "ٱلۡكَرِيمُ",
    "arabicMeaning": "الكريم",
    "hindiName": "अल-करीम",
    "hindiMeaning": "उदार",
    "description": {
      "english": "Allah is the Generous, the Noble.",
      "bangla": "আল্লাহ উদার, মহান।",
      "arabic": "ٱللَّهُ ٱلۡكَرِيمُ",
      "hindi": "अल्लाह उदार, उदार हैं।"
    },
    "quranAyat": {
      "english": "And if whatever trees upon the earth were pens and the sea [was ink], replenished thereafter by seven [more] seas, the words of Allah would not be exhausted. Indeed, Allah is Exalted in Might and Wise. (Surah Luqman 31:27)",
      "bangla": "যদি পৃথিবীর উপর যে যে গাছ আছে সেগুলো কলম হতে এবং সমুদ্র [কলমের] মধ্যে মাথায় দেওয়া হয়, পরে তারা আরও সাতটি সমুদ্র দ্বারা পুনর্বিধায়িত হত, তবে আল্লাহের কথাগুলি কখনোই অব্যাহত হতে পারবে না। নিশ্চয়, আল্লাহ প্রশস্ত ও জ্ঞানী। (সূরা লুকমান ৩১:২৭)",
      "arabic": "وَلَوۡ أَنَّمَا فِى ٱلۡأَرۡضِ مِن شَجَرَةٍ أَقۡلَـٰمُ وَٱلۡبَحۡرُ يَمُدُّهُ ۥ مِنۡہُ بَعۡدُ سَبۡعَةُ أَبۡحُرٍ۬ مَّا نَفِدَتۡ كَلِمَـٰتُ ٱللَّهِ‌ۗ إِنَّ ٱللَّهَ عَزِيزٌ حَڪِيمٌ۬ (سورة لقمان 31:27)",
      "hindi": "और अगर पृथ्वी पर जो कुछ पेड़ हैं वह सब कलम होते और समुद्र [स्याही होता], उसके बाद उसे सात [और] समुद्रों द्वारा पुनः पूरा किया जाता, तो भी अल्लाह के वचन कभी समाप्त नहीं होते। निश्चय ही, अल्लाह शक्तिशाली और ज्ञानी हैं। (सूरह लुकमान 31:27)"
    }
  },
  {
    "index": 43,
    "name": "Ar-Raqib",
    "meaning": "The Watchful",
    "banglaName": "আর-রাকিব",
    "banglaMeaning": "নিখোজ",
    "arabicName": "ٱلرَّقِيبُ",
    "arabicMeaning": "الرقيب",
    "hindiName": "अर-रकीब",
    "hindiMeaning": "निगेहबान",
    "description": {
      "english": "Allah is the Watchful, the Ever-Watchful.",
      "bangla": "আল্লাহ নিখোজ, চিরকাল নিখোজ।",
      "arabic": "ٱللَّهُ ٱلرَّقِيبُ",
      "hindi": "अल्लाह निगेहबान, हमेशा निगेहबान हैं।"
    },
    "quranAyat": {
      "english": "And We have already created man and know what his soul whispers to him, and We are closer to him than [his] jugular vein. (Surah Qaf 50:16)",
      "bangla": "আমরা মানুষ সৃষ্টি করেছি এবং জানি যে তার আত্মা তার সাথে কীভাবে আলাপ করে, এবং আমরা তার জঘন্য নদীর থেকে তাকে কাছে রেখেছি। (সূরা কাফ ৫০:১৬)",
      "arabic": "وَلَقَدۡ خَلَقۡنَا ٱلۡإِنسَـٰنَ وَنَعۡلَمُ مَا تُوَسۡوِسُ بِهِۦ نَفۡسُهُ ۥ‌ۖ وَنَحۡنُ أَقۡرَبُ إِلَيۡهِ مِنۡ حَبۡلِ ٱلۡوَرِيدِ (سورة ق 50:16)",
      "hindi": "और हमने इंसान की पैदाइश कर दी है और जानते हैं कि उसकी आत्मा उसके साथ कैसे चुगली करती है, और हम उसके जुगलर वेन से भी उसके करीब हैं। (सूरह काफ 50:16)"
    }
  },
  {
    "index": 44,
    "name": "Al-Mujib",
    "meaning": "The Responsive",
    "banglaName": "আল-মুজিব",
    "banglaMeaning": "প্রতিকারক",
    "arabicName": "ٱلۡمُجِيبُ",
    "arabicMeaning": "المجيب",
    "hindiName": "अल-मुजीब",
    "hindiMeaning": "जवाब देनेवाला",
    "description": {
      "english": "Allah is the Responsive, the Answerer.",
      "bangla": "আল্লাহ প্রতিকারক, প্রতিকারক।",
      "arabic": "ٱللَّهُ ٱلۡمُجِيبُ",
      "hindi": "अल्लाह जवाब देनेवाला, जवाब देनेवाला हैं।"
    },
    "quranAyat": {
      "english": "And your Lord says, \"Call upon Me; I will respond to you.\" Indeed, those who disdain My worship will enter Hell [rendered] contemptible. (Surah Ghafir 40:60)",
      "bangla": "এবং তোমার প্রভু বলে, \"আমার উপর আহবান করো; আমি তোমাদের উত্তর দেব।\" নিশ্চয়, যারা আমার উপাসনা হিসেবে অবমান করে, তারা অপমানজনক জহিন্নামে প্রবেশ করবে। (সূরা গাফির ৪০:৬০)",
      "arabic": "وَقَالَ رَبُّڪُمُ ٱدۡعُونِىٓ أَسۡتَجِبۡ لَكُمۡ‌ۚ إِنَّ ٱلَّذِينَ يَسۡتَكۡبِرُونَ عَنۡ عِبَادَتِى سَيَدۡخُلُونَ جَهَنَّمَ دَاخِرِينَ (سورة غافر 40:60)",
      "hindi": "और तुम्हारे प्रभु कहता है, \"मुझ पर पुकारो; मैं तुम्हें जवाब दूंगा।\" बेशक, जो लोग मेरी पूजा को तिरस्कृत करते हैं, वे जहन्नुम में दखल पाएँगे। (सूरह गाफिर 40:60)"
    }
  },
  {
    "index": 45,
    "name": "Al-Wasi",
    "meaning": "The All-Encompassing",
    "banglaName": "আল-ওয়াসি",
    "banglaMeaning": "বহুমুখী",
    "arabicName": "ٱلۡوَٰسِعُ",
    "arabicMeaning": "الواسع",
    "hindiName": "अल-वासी",
    "hindiMeaning": "बहुमुखी",
    "description": {
      "english": "Allah is the All-Encompassing, the Vast.",
      "bangla": "আল্লাহ বহুমুখী, প্রশান্ত।",
      "arabic": "ٱللَّهُ ٱلۡوَٰسِعُ",
      "hindi": "अल्लाह बहुमुखी, विशाल हैं।"
    },
    "quranAyat": {
      "english": "And if whatever trees upon the earth were pens and the sea [was ink], replenished thereafter by seven [more] seas, the words of Allah would not be exhausted. Indeed, Allah is Exalted in Might and Wise. (Surah Luqman 31:27)",
      "bangla": "যদি পৃথিবীর উপর যে যে গাছ আছে সেগুলো কলম হতে এবং সমুদ্র [কলমের] মধ্যে মাথায় দেওয়া হয়, পরে তারা আরও সাতটি সমুদ্র দ্বারা পুনর্বিধায়িত হত, তবে আল্লাহের কথাগুলি কখনোই অব্যাহত হতে পারবে না। নিশ্চয় আল্লাহ প্রশস্ত ও জ্ঞানী। (সূরা লুকমান ৩১:২৭)",
      "arabic": "وَلَوۡ أَنَّمَا فِى ٱلۡأَرۡضِ مِن شَجَرَةٍ أَقۡلَـٰمُ وَٱلۡبَحۡرُ يَمُدُّهُ ۥ مِنۡہُ بَعۡدُ سَبۡعَةُ أَبۡحُرٍ۬ مَّا نَفِدَتۡ كَلِمَـٰتُ ٱللَّهِ‌ۗ إِنَّ ٱللَّهَ عَزِيزٌ حَڪِيمٌ۬ (سورة لقمان 31:27)",
      "hindi": "और अगर पृथ्वी पर जो कुछ पेड़ हैं वह सब कलम होते और समुद्र [स्याही होता], उसके बाद उसे सात [और] समुद्रों द्वारा पुनः पूरा किया जाता, तो भी अल्लाह के वचन कभी समाप्त नहीं होते। निश्चय ही, अल्लाह शक्तिशाली और ज्ञानी हैं। (सूरह लुकमान 31:27)"
    }
  }, {
    "index": 46,
    "name": "Al-Hakam",
    "meaning": "The Judge",
    "banglaName": "আল-হাকম",
    "banglaMeaning": "আদালতদার",
    "arabicName": "ٱلۡحَكَمُ",
    "arabicMeaning": "الحكم",
    "hindiName": "अल-हकम",
    "hindiMeaning": "न्यायक",
    "description": {
      "english": "Allah is the Judge, the Ultimate Arbiter.",
      "bangla": "আল্লাহ আদালতদার, চূড়ান্ত ন্যায়কর্তা।",
      "arabic": "ٱللَّهُ ٱلۡحَكَمُ",
      "hindi": "अल्लाह न्यायक, अंतिम न्यायकर्ता हैं।"
    },
    "quranAyat": {
      "english": "And He is the subjugator over His servants, and He is the Wise, the Acquainted [with all]. (Surah Al-An'am 6:18)",
      "bangla": "তিনি তার কর্মচারীদের উপর প্রভুত্ব বোধ করেন, এবং তিনি জ্ঞানী, সকলের জানালেন। (সূরা আল-আনাম 6:18)",
      "arabic": "وَهُوَ ٱلۡقَـٰهِرُ فَوۡقَ عِبَادِهِۦ‌ۖ وَهُوَ ٱلۡحَكِيمُ ٱلۡخَبِيرُ (سورة الأنعام 6:18)",
      "hindi": "और वह अपने बन्दों पर ज़बरदस्ती करनेवाला है, और वह बुद्धिमान, सभी को अच्छी तरह जाननेवाला है। (सूरह अल-अन'आम 6:18)"
    }
  },
  {
    "index": 47,
    "name": "Al-Wadud",
    "meaning": "The Loving",
    "banglaName": "আল-ওয়াদুদ",
    "banglaMeaning": "প্রিয়তম",
    "arabicName": "ٱلۡوَدُودُ",
    "arabicMeaning": "الودود",
    "hindiName": "अल-वादूद",
    "hindiMeaning": "प्रिय",
    "description": {
      "english": "Allah is the Loving, the Affectionate.",
      "bangla": "আল্লাহ প্রিয়, স্নেহশীল।",
      "arabic": "ٱللَّهُ ٱلۡوَدُودُ",
      "hindi": "अल्लाह प्रिय, स्नेहशील हैं।"
    },
    "quranAyat": {
      "english": "Say, [O Muhammad], \"If you should love Allah, then follow me, [so] Allah will love you and forgive you your sins. And Allah is Forgiving and Merciful.\" (Surah Al-Imran 3:31)",
      "bangla": "বলুন, [হে মুহাম্মদ], \"যদি তুমি আল্লাহকে ভালোবাসো, তবে আমার অনুসরণ করো, [তাহলে] আল্লাহ তোমাকে ভালোবাসবেন এবং তোমার পাপ ক্ষমা করবেন। আর আল্লাহ ক্ষমাশীল এবং দয়ালু।\" (সূরা আল-ইমরান 3:31)",
      "arabic": "قُلۡ إِن كُنتُمۡ تُحِبُّونَ ٱللَّهَ فَٱتَّبِعُونِى يُحۡبِبۡكُمُ ٱللَّهُ وَيَغۡفِرۡ لَكُمۡ ذُنُوبَكُمۡ‌ۗ وَٱللَّهُ غَفُورٌ۬ رَّحِيمٌ۬ (سورة آل عمران 3:31)",
      "hindi": "कहो, [ओ मुहम्मद], \"अगर तुम अल्लाह को प्यार करते हो, तो मेरा पालन करो, [तो] अल्लाह तुम्हें प्यार करेगा और तुम्हारे पापों को माफ कर देगा। और अल्लाह बख्शनेवाला और दयालु है।\" (सूरह आल-इमरान 3:31)"
    }
  },
  {
    "index": 48,
    "name": "Al-Majid",
    "meaning": "The Glorious",
    "banglaName": "আল-মাজিদ",
    "banglaMeaning": "মহৎ",
    "arabicName": "ٱلۡمَجِيدُ",
    "arabicMeaning": "المجيد",
    "hindiName": "अल-माजिद",
    "hindiMeaning": "महान",
    "description": {
      "english": "Allah is the Glorious, the Illustrious.",
      "bangla": "আল্লাহ মহৎ, সুপ্রভাত।",
      "arabic": "ٱللَّهُ ٱلۡمَجِيدُ",
      "hindi": "अल्लाह महान, उज्ज्वल हैं।"
    },
    "quranAyat": {
      "english": "And to Allah belongs the east and the west. So wherever you [might] turn, there is the Face of Allah. Indeed, Allah is all-Encompassing and Knowing. (Surah Al-Baqarah 2:115)",
      "bangla": "আল্লাহর দিক পূর্বে এবং পশ্চিমের দিকেই। সুতরাং তুমি যেতে পারো, সেখানেই আল্লাহর মুখ। সত্যিই, আল্লাহ সবকিছুতে বহুমুখী এবং জ্ঞানী। (সূরা আল-বাকারাহ ২:১১৫)",
      "arabic": "وَلِلَّهِ ٱلۡمَشۡرِقُ وَٱلۡمَغۡرِبُ‌ۚ فَأَيۡنَمَا تُوَلُّواْ فَثَمَّ وَجۡهُ ٱللَّهِ‌ۚ إِنَّ ٱللَّهَ وَٰسِعٌ عَلِيمٌ۬ (سورة البقرة 2:115)",
      "hindi": "और ईश्वर की पूर्व ओर और पश्चिम ओर है। तो जहां भी तुम उठोगे, वहाँ अल्लाह का चेहरा है। निश्चय ही, अल्लाह सभी चीजों को बहुमुखी हैं और ज्ञानी हैं। (सूरह अल-बकराह 2:115)"
    }
  },
  {
    "index": 49,
    "name": "Al-Ba'ith",
    "meaning": "The Resurrector",
    "banglaName": "আল-বাইথ",
    "banglaMeaning": "পুনরুত্থানকারী",
    "arabicName": "ٱلۡبَاعِثُ",
    "arabicMeaning": "الباعث",
    "hindiName": "अल-बाईथ",
    "hindiMeaning": "पुनर्जीवित करनेवाला",
    "description": {
      "english": "Allah is the Resurrector, the Raiser of the Dead.",
      "bangla": "আল্লাহ পুনরুত্থানকারী, মৃত্যুবারকারক।",
      "arabic": "ٱللَّهُ ٱلۡبَاعِثُ",
      "hindi": "अल्लाह पुनर्जीवित करनेवाला, मृत्युवर्जित करनेवाला हैं।"
    },
    "quranAyat": {
      "english": "Indeed, We have written in the Zabur [i.e., Psalms], after the [previous] mention, that the land [of Paradise] is inherited by My righteous servants. (Surah Al-Anbiya 21:105)",
      "bangla": "নিশ্চয়, আমি জাবুর [অর্থাৎ ভাগবত], আগের উল্লেখের পরে লিখেছি, যে আমার সত্যান্বেষী কর্মচারীরা আমার অধিকারের। (সূরা আল-আনবিয়া ২১:১০৫)",
      "arabic": "لَقَدۡ كَتَبۡنَا فِى ٱلزَّبُورِ مِنۡہُ بَعۡدَ ٱلذِّڪۡرِ أَنَّ ٱلۡأَرۡضَ يَرِثُهَا عِبَادِىَ ٱلصَّـٰلِحُونَ (سورة الأنبياء 21:105)",
      "hindi": "निश्चय ही, हमने ज़ाबूर [अर्थात भगवत] में उसके पूर्व स्मरण के बाद लिखा है, कि पृथ्वी [स्वर्ग की] मेरे धर्मी भक्तों के द्वारा विरासत में आती है। (सूरह अल-अनबिया 21:105)"
    }
  },
  {
    "index": 50,
    "name": "Ash-Shahid",
    "meaning": "The Witness",
    "banglaName": "আশ-শাহিদ",
    "banglaMeaning": "সাক্ষী",
    "arabicName": "ٱلشَّهِيدُ",
    "arabicMeaning": "الشهيد",
    "hindiName": "अश-शाहिद",
    "hindiMeaning": "गवाह",
    "description": {
      "english": "Allah is the Witness, the All-Observer.",
      "bangla": "আল্লাহ সাক্ষী, সর্বদর্শী।",
      "arabic": "ٱللَّهُ ٱلشَّهِيدُ",
      "hindi": "अल्लाह गवाह, सब देखनेवाला हैं।"
    },
    "quranAyat": {
      "english": "Or do they say [about the Prophet], \"He invented it?\" Say, \"Then bring forth a surah like it and call upon [for assistance] whomever you can besides Allah, if you should be truthful.\" (Surah Yunus 10:38)",
      "bangla": "বা তারা [নবীর সম্পর্কে] বলে, \"সে এটা মিথ্যা বলেছিল?\" বলুন, \"তাহলে সেইরকম একটি সূরা নিয়ে আসুন এবং সত্যিকারের তোমার পাশে কেউ আল্লাহের ছাড়া যদি সত্যিক হও তবে তার জন্য আহবান করো\" (সূরা ইউনুস ১০:৩৮)",
      "arabic": "أَمۡ يَقُولُونَ ٱفۡتَرَىٰهُ‌ۖ قُلۡ فَأۡتُواْ بِسُورَةٍ۬ مِّثۡلِهِۦ وَٱدۡعُواْ مَنِ ٱسۡتَطَعۡتُم مِّن دُونِ ٱللَّهِ إِن كُنتُمۡ صَـٰدِقِينَ (سورة يونس 10:38)",
      "hindi": "या वे [पैगम्बर के बारे में] कहते हैं, \"उसने यह झूठ बोला?\" कहो, \"तो फिर उसके जैसी एक सूरा लाओ और यदि तुम सच्चे हो, तो अल्लाह के सिवाय किसी को भी पुकारो\" (सूरह यूनुस 10:38)"
    }
  },{
    "index": 51,
    "name": "Al-Haqq",
    "meaning": "The Truth",
    "banglaName": "আল-হাক্ক",
    "banglaMeaning": "সত্য",
    "arabicName": "ٱلۡحَقُّ",
    "arabicMeaning": "الحق",
    "hindiName": "अल-हक",
    "hindiMeaning": "सच्चाई",
    "description": {
      "english": "Allah is the Truth, the Reality.",
      "bangla": "আল্লাহ সত্য, বাস্তবতা।",
      "arabic": "ٱللَّهُ ٱلۡحَقُّ",
      "hindi": "अल्लाह सच्चाई, वास्तविकता हैं।"
    },
    "quranAyat": {
      "english": "That is because Allah is the Truth, and that what they call upon other than Him is falsehood, and because Allah is the Most High, the Grand. (Surah Al-Hajj 22:62)",
      "bangla": "এটি তাই যে, আল্লাহ সত্য, এবং তারা যা আল্লাহের বাইরে আর কোন নাম দিয়ে আহবান করে, তা মিথ্যা, এবং যে আল্লাহ সর্বোচ্চ, মহান। (সূরা আল-হজ্জ ২২:৬২)",
      "arabic": "ذَٰلِكَ بِأَنَّ ٱللَّهَ هُوَ ٱلۡحَقُّ‌ۖ وَأَنَّ مَا يَدۡعُونَ مِن دُونِهِ ٱلۡبَـٰطِلُ‌ۖ وَأَنَّ ٱللَّهَ هُوَ ٱلۡعَلِىُّ ٱلۡكَبِيرُ (سورة الحج 22:62)",
      "hindi": "यह इसलिए है कि अल्लाह सच्चाई हैं, और वह जो लोग उसके अलावा कोई और बुलाते हैं, वह झूठ हैं, और क्योंकि अल्लाह सर्वोच्च, महान हैं। (सूरह अल-हज्ज 22:62)"
    }
  },
  {
    "index": 52,
    "name": "Al-Wakil",
    "meaning": "The Trustee",
    "banglaName": "আল-ওয়াকীল",
    "banglaMeaning": "বিশ্বাসপ্রাপ্তকারী",
    "arabicName": "ٱلۡوَكِيلُ",
    "arabicMeaning": "الوكيل",
    "hindiName": "अल-वकील",
    "hindiMeaning": "विश्वासकर्ता",
    "description": {
      "english": "Allah is the Trustee, the Disposer of Affairs.",
      "bangla": "আল্লাহ বিশ্বাসপ্রাপ্তকারী, ব্যবস্থাপক।",
      "arabic": "ٱللَّهُ ٱلۡوَكِيلُ",
      "hindi": "अल्लाह विश्वासकर्ता, प्रबंधक हैं।"
    },
    "quranAyat": {
      "english": "And upon Allah let those who would rely [indeed] rely. (Surah Ibrahim 14:11)",
      "bangla": "আর আল্লাহের উপর যারা ভরসা করতে চান [যারা সত্যিই] ভরসা করুন। (সূরা ইব্রাহিম ১৪:১১)",
      "arabic": "وَعَلَى ٱللَّهِ فَلۡيَتَوَكَّلِ ٱلۡمُؤۡمِنُونَ (سورة إبراهيم 14:11)",
      "hindi": "और अल्लाह पर वही भरोसा रखने वाले भरोसा रखें। (सूरह इब्राहिम 14:11)"
    }
  },
  {
    "index": 53,
    "name": "Al-Qawiyy",
    "meaning": "The Mighty",
    "banglaName": "আল-কাবীর",
    "banglaMeaning": "শক্তিশালী",
    "arabicName": "ٱلۡقَوِىُّ",
    "arabicMeaning": "القوي",
    "hindiName": "अल-कवी",
    "hindiMeaning": "शक्तिशाली",
    "description": {
      "english": "Allah is the Mighty, the Strong.",
      "bangla": "আল্লাহ শক্তিশালী, তেজস্বী।",
      "arabic": "ٱللَّهُ ٱلۡقَوِىُّ",
      "hindi": "अल्लाह शक्तिशाली, मजबूत हैं।"
    },
    "quranAyat": {
      "english": "And if they deny you, [O Muhammad], then say, \"For me are my deeds, and for you are your deeds. You are disassociated from what I do, and I am disassociated from what you do.\" (Surah Yunus 10:41)",
      "bangla": "আর যদি তারা [হে মুহাম্মদ], তোমাকে প্রত্যাখ্যান করে, তাহলে বলুন, \"আমার কাজের জন্য আমার, আর তোমাদের কাজের জন্য তোমাদের। তুমি আমার কাজের প্রতি আলাদা, আর আমি তোমার কাজের প্রতি আলাদা।\" (সূরা ইউনুস 10:৪১)",
      "arabic": "وَإِن كَذَّبُوكَ فَقُل لِّىٓ عَمَلِى وَلَكُمۡ عَمَلُكُمۡ‌ۖ أَنتُم بَرِيٓءُونَ مِمَّآ أَعۡمَلُ وَأَنَا۟ بَرِىٓءٌ۬ مِّمَّا تَعۡمَلُونَ (سورة يونس 10:41)",
      "hindi": "और अगर वे तुम्हें झूठा कहें, [ओ मुहम्मद], तो कहो, \"मेरे लिए मेरे काम हैं, और तुम्हारे लिए तुम्हारे काम हैं। तुम मेरे काम से अलग हो, और मैं तुम्हारे काम से अलग हूँ।\" (सूरह यूनुस 10:41)"
    }
  },
  {
    "index": 54,
    "name": "Al-Matin",
    "meaning": "The Firm",
    "banglaName": "আল-মাতিন",
    "banglaMeaning": "দৃঢ়",
    "arabicName": "ٱلۡمَتِينُ",
    "arabicMeaning": "المتين",
    "hindiName": "अल-मतीन",
    "hindiMeaning": "मज़बूत",
    "description": {
      "english": "Allah is the Firm, the Steadfast.",
      "bangla": "আল্লাহ দৃঢ়, অবিচল।",
      "arabic": "ٱللَّهُ ٱلۡمَتِينُ",
      "hindi": "अल्लाह मज़बूत, अटल हैं।"
    },
    "quranAyat": {
      "english": "And Allah is the Subjugator of the Great, above His servants, and He sends over you guardian-angels until, when death comes to one of you, Our messengers take him, and they do not fail [in their duties]. (Surah Al-An'am 6:61)",
      "bangla": "আর আল্লাহ মহান কর্তনী, তার কর্মচারীদের উপর উচ্চ, এবং তিনি তোমার ওপর প্রতিরক্ষা-দেবদূত প্রেরণ করেন যতক্ষণ না, যখন তোমাদের মধ্যে মৃত্যু ঘটে, আমাদের দূতরা তাকে নেওয়া এবং তারা [তাদের দায়িত্বে] ব্যর্থ হয় না। (সূরা আল-আনাম 6:61)",
      "arabic": "وَهُوَ ٱلۡقَاهِرُ فَوۡقَ عِبَادِهِۦ‌ۖ وَيُرۡسِلُ عَلَيۡڪُمۡ حَفَظَةً حَتَّىٰٓ إِذَا جَآءَ أَحَدَكُمُ ٱلۡمَوۡتُ تَوَفَّتۡهُ رُسُلُنَا وَهُمۡ لَا يُفَرِّطُونَ (سورة الأنعام 6:61)",
      "hindi": "और अल्लाह महान कर्तनी वाले हैं, अपने बन्दों के ऊपर, और वह तुम पर रक्षक-दूत भेजते हैं, जब तक कि तुम में से किसी के पास मौत न आए, हमारे दूत उसे लेकर आते हैं और वे [अपने कर्तव्यों में] नाकाम नहीं होते। (सूरह अल-अन'आम 6:61)"
    }
  },
  {
    "index": 55,
    "name": "Al-Waliyy",
    "meaning": "The Patron",
    "banglaName": "আল-ওয়ালী",
    "banglaMeaning": "পরিচালক",
    "arabicName": "ٱلۡوَلِىُّ",
    "arabicMeaning": "الولي",
    "hindiName": "अल-वली",
    "hindiMeaning": "संरक्षक",
    "description": {
      "english": "Allah is the Patron, the Protector.",
      "bangla": "আল্লাহ পরিচালক, রক্ষক।",
      "arabic": "ٱللَّهُ ٱلۡوَلِىُّ",
      "hindi": "अल्लाह संरक्षक, संरक्षक हैं।"
    },
    "quranAyat": {
      "english": "And who is better in religion than one who submits himself to Allah while being a doer of good and follows the religion of Abraham, inclining toward truth? And Allah took Abraham as an intimate friend. (Surah An-Nisa 4:125)",
      "bangla": "ধর্মে কে বেশি সৎসাধু যাহার মধ্যে তিনি ভালো কাজ করতে সাবধানতা পাওয়া আল্লাহের উপর নিজেকে অধীন করে দিয়ে, এবং আব্রাহামের ধর্ম অনুসরণ করে, সত্যের দিকে নম্রভাবে মুখ তোলে? আর আল্লাহ আব্রাহামকে একটি প্রিয় বন্ধু হিসেবে গ্রহণ করেছিল। (সূরা নিসা ৪:১২৫)",
      "arabic": "وَمَنۡ أَحۡسَنُ دِينً۬ا مِّمَّنۡ أَسۡلَمَ وَجۡهَهُ ۥ لِلَّهِ وَهُوَ مُحۡسِنٌ۬ وَٱتَّبَعَ مِلَّةَ إِبۡرَٲهِـِٔيمَ حَنِيفً۬ا‌ۗ وَٱتَّخَذَ ٱللَّهُ إِبۡرَٲهِـِٔيمَ خَلِيلاً۬ (سورة النساء 4:125)",
      "hindi": "और धर्म में कौन बेहतर है जो अल्लाह को समर्पित होकर भले कार्य करता है और इस्लाम के मार्ग का अनुसरण करता है, सत्य की ओर मुड़ता है? और अल्लाह ने इब्राहीम को एक घनिष्ठ मित्र के रूप में ग्रहण किया। (सूरह अन-निसा 4:125)"
    }
  },];